# Generated by Django 4.2.11 on 2026-01-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('education', models.CharField(choices=[('10th', '10th Grade'), ('12th', '12th Grade'), ('diploma', 'Diploma'), ('bsc_cs', 'B.Sc Computer Science'), ('bsc_it', 'B.Sc IT'), ('bca', 'BCA'), ('bcom', 'B.Com'), ('btech', 'B.Tech'), ('post_graduate', 'Post Graduate'), ('other', 'Other')], max_length=20)),
                ('course', models.CharField(max_length=100)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
