# Generated by Django 4.2.11 on 2026-01-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0002_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='terms_accepted',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.CharField(choices=[('Excel for Data Analysis', 'Excel for Data Analysis'), ('SQL for Data Analysis', 'SQL for Data Analysis'), ('Python Development', 'Python Development'), ('Data Visualization', 'Data Visualization'), ('Azure Fundamentals', 'Azure Fundamentals'), ('Azure AI Fundamentals', 'Azure AI Fundamentals'), ('Power Platform', 'Power Platform'), ('Security & Compliance', 'Security & Compliance'), ('Professional Development', 'Professional Development')], max_length=100),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='education',
            field=models.CharField(choices=[('10th', '10th Grade'), ('12th', '12th Grade'), ('diploma', 'Diploma'), ('bsc_cs', 'B.Sc Computer Science'), ('bsc_it', 'B.Sc IT'), ('bca', 'BCA'), ('bcom', 'B.Com'), ('btech', 'B.Tech'), ('post_graduate', 'Post Graduate'), ('other', 'Other')], max_length=50),
        ),
    ]
