# Generated by Django 4.2.11 on 2026-01-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0009_course_duration_course_format_course_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
