# Generated by Django 4.2.11 on 2026-01-08 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0010_course_contact_number_course_whatsapp_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Highlight Title (example: 50+ Functions)')),
                ('description', models.CharField(max_length=200, verbose_name='Short Description (example: Master essential Excel functions)')),
                ('icon', models.CharField(choices=[('bi-code-slash', 'Code / Functions'), ('bi-bar-chart-steps', 'Projects'), ('bi-people', 'Mentor Support'), ('bi-award', 'Certification'), ('bi-graph-up', 'Analytics'), ('bi-laptop', 'Practical Training')], max_length=50, verbose_name='Icon (visual symbol)')),
                ('color', models.CharField(choices=[('primary', 'Blue'), ('success', 'Green'), ('warning', 'Yellow'), ('info', 'Sky Blue'), ('danger', 'Red')], max_length=20, verbose_name='Background Color')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='yume_site.course', verbose_name='Related Course')),
            ],
        ),
    ]
