# Generated by Django 4.2.11 on 2026-01-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0011_coursehighlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='format',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_hours',
        ),
        migrations.RemoveField(
            model_name='course',
            name='whatsapp_number',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_url',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='CourseHighlight',
        ),
    ]
