# Generated by Django 4.2.11 on 2026-01-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0012_remove_course_contact_number_remove_course_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='format',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='total_hours',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_url',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
