# Generated by Django 4.2.11 on 2026-01-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0013_course_contact_number_course_duration_course_format_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.AddField(
            model_name='course',
            name='card_description',
            field=models.TextField(default='', help_text='Shown only on course cards'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='overview',
            field=models.TextField(blank=True, help_text='Main description for course detail page'),
        ),
        migrations.AlterField(
            model_name='course',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Shown below enrollment card', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Shown below course title', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Example: 918792885644', max_length=20),
        ),
    ]
