# Generated by Django 4.2.11 on 2026-01-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0014_remove_course_description_course_card_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='card_description',
            field=models.TextField(blank=True, help_text='Shown only on course cards'),
        ),
    ]
