# Generated by Django 4.2.11 on 2026-01-08 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0015_alter_course_card_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='Bootstrap icon class, e.g. bi bi-code-slash', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='yume_site.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
