# Generated by Django 4.2.11 on 2026-01-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0016_coursehighlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursehighlight',
            name='icon_class',
            field=models.CharField(choices=[('bi bi-code-slash', 'Code / Functions'), ('bi bi-bar-chart-steps', 'Charts / Projects'), ('bi bi-people', 'Mentor / Support'), ('bi bi-award', 'Certification / Achievement'), ('bi bi-laptop', 'Online / Live'), ('bi bi-lightning-charge', 'Fast / Intensive'), ('bi bi-briefcase', 'Career / Job')], default='bi bi-code-slash', help_text='Select an icon', max_length=100),
        ),
    ]
