# Generated by Django 4.2.11 on 2026-01-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0017_alter_coursehighlight_icon_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursehighlight',
            name='icon_class',
            field=models.CharField(choices=[('bi bi-code-slash', 'Coding & Functions'), ('bi bi-bar-chart-steps', 'Charts & Analytics'), ('bi bi-folder-check', 'Hands-on Projects'), ('bi bi-people', 'Mentor Support'), ('bi bi-award', 'Certification'), ('bi bi-laptop', 'Online Learning'), ('bi bi-clock-history', 'Flexible Timing'), ('bi bi-briefcase', 'Career Focused'), ('bi bi-lightning-charge', 'Fast Track'), ('bi bi-patch-check', 'Industry Ready')], default='bi bi-code-slash', max_length=100, verbose_name='Icon'),
        ),
    ]
