# Generated by Django 4.2.11 on 2026-01-08 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0018_alter_coursehighlight_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=255)),
                ('meta_info', models.CharField(blank=True, help_text='Example: 40 Hours • Beginner Level', max_length=100)),
                ('badge_color', models.CharField(default='primary', help_text='Bootstrap color: primary, success, warning', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_months', to='yume_site.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='yume_site.curriculummonth')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='yume_site.curriculumsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
