# Generated by Django 4.2.11 on 2026-01-10 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0019_curriculummonth_curriculumsection_curriculumtopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculummonth',
            name='badge_color',
            field=models.CharField(choices=[('primary', 'Blue'), ('success', 'Green'), ('warning', 'Yellow'), ('danger', 'Red'), ('info', 'Light Blue'), ('secondary', 'Gray'), ('dark', 'Dark')], default='primary', help_text='Choose a color label for this month', max_length=20),
        ),
        migrations.AlterField(
            model_name='curriculummonth',
            name='course',
            field=models.ForeignKey(help_text='Select which course this month belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_months', to='yume_site.course'),
        ),
        migrations.AlterField(
            model_name='curriculummonth',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this month on website'),
        ),
        migrations.AlterField(
            model_name='curriculummonth',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Controls the display order'),
        ),
        migrations.AlterField(
            model_name='curriculummonth',
            name='subtitle',
            field=models.CharField(help_text='Example: Excel Foundations & Data Basics', max_length=255),
        ),
        migrations.AlterField(
            model_name='curriculummonth',
            name='title',
            field=models.CharField(help_text='Example: Month 1, Month 2', max_length=50),
        ),
        migrations.AlterField(
            model_name='curriculumsection',
            name='month',
            field=models.ForeignKey(help_text='This section belongs to which month', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='yume_site.curriculummonth'),
        ),
        migrations.AlterField(
            model_name='curriculumsection',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Controls section order inside the month'),
        ),
        migrations.AlterField(
            model_name='curriculumsection',
            name='title',
            field=models.CharField(help_text='Example: Week 1–2: Core Fundamentals', max_length=200),
        ),
        migrations.AlterField(
            model_name='curriculumtopic',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Controls topic order'),
        ),
        migrations.AlterField(
            model_name='curriculumtopic',
            name='section',
            field=models.ForeignKey(help_text='This topic belongs to which section', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='yume_site.curriculumsection'),
        ),
        migrations.AlterField(
            model_name='curriculumtopic',
            name='title',
            field=models.CharField(help_text='Example: Excel Interface & Navigation', max_length=255),
        ),
    ]
