# Generated by Django 4.2.11 on 2026-01-10 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0020_alter_curriculummonth_badge_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('color', models.CharField(choices=[('primary', 'Blue'), ('success', 'Green'), ('warning', 'Yellow'), ('info', 'Sky Blue')], default='primary', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='yume_site.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseLearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('color', models.CharField(choices=[('primary', 'Blue'), ('success', 'Green'), ('warning', 'Yellow'), ('info', 'Sky Blue')], default='primary', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='yume_site.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
