# Generated by Django 4.2.11 on 2026-01-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0021_coursetool_courselearningoutcome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courselearningoutcome',
            options={'ordering': ['order'], 'verbose_name': 'Learning Outcome', 'verbose_name_plural': 'Learning Outcomes'},
        ),
        migrations.AlterModelOptions(
            name='coursetool',
            options={'ordering': ['order'], 'verbose_name': 'Tool / Technology', 'verbose_name_plural': 'Tools & Technologies'},
        ),
        migrations.AlterField(
            model_name='courselearningoutcome',
            name='color',
            field=models.CharField(choices=[('primary', 'Blue'), ('success', 'Green'), ('warning', 'Yellow'), ('info', 'Sky Blue')], default='primary', help_text='Controls the dot & border color', max_length=20),
        ),
        migrations.AlterField(
            model_name='courselearningoutcome',
            name='description',
            field=models.TextField(help_text='One or two lines explaining this outcome'),
        ),
        migrations.AlterField(
            model_name='courselearningoutcome',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Controls vertical order (top to bottom)'),
        ),
        migrations.AlterField(
            model_name='courselearningoutcome',
            name='title',
            field=models.CharField(help_text='Short heading shown in bold (example: Data Analysis Mastery)', max_length=255),
        ),
        migrations.AlterField(
            model_name='coursetool',
            name='color',
            field=models.CharField(choices=[('primary', 'Blue'), ('success', 'Green'), ('warning', 'Yellow'), ('info', 'Sky Blue')], default='primary', help_text='Left border color', max_length=20),
        ),
        migrations.AlterField(
            model_name='coursetool',
            name='description',
            field=models.TextField(help_text='What this tool is used for in the course'),
        ),
        migrations.AlterField(
            model_name='coursetool',
            name='name',
            field=models.CharField(help_text='Tool name (example: Microsoft Excel)', max_length=255),
        ),
        migrations.AlterField(
            model_name='coursetool',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Controls order in list'),
        ),
    ]
