# Generated by Django 4.2.11 on 2026-01-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0022_alter_courselearningoutcome_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselearningoutcome',
            name='color',
            field=models.CharField(choices=[('primary', 'Blue'), ('success', 'Green'), ('warning', 'Yellow'), ('info', 'Sky Blue')], default='primary', help_text='Controls the circle & border color on website', max_length=20, verbose_name='Dot Color'),
        ),
        migrations.AlterField(
            model_name='courselearningoutcome',
            name='description',
            field=models.TextField(help_text='1–2 short lines explaining this outcome', verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='courselearningoutcome',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower number = shows first', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='courselearningoutcome',
            name='title',
            field=models.CharField(help_text='Example: Data Analysis Mastery', max_length=255, verbose_name='Outcome Title'),
        ),
        migrations.AlterField(
            model_name='coursetool',
            name='color',
            field=models.CharField(choices=[('primary', 'Blue'), ('success', 'Green'), ('warning', 'Yellow'), ('info', 'Sky Blue')], default='primary', help_text='Controls the left border color', max_length=20, verbose_name='Left Border Color'),
        ),
        migrations.AlterField(
            model_name='coursetool',
            name='description',
            field=models.TextField(help_text='Explain how this tool is used in the course', verbose_name='Usage Description'),
        ),
        migrations.AlterField(
            model_name='coursetool',
            name='name',
            field=models.CharField(help_text='Example: Microsoft Excel', max_length=255, verbose_name='Tool Name'),
        ),
        migrations.AlterField(
            model_name='coursetool',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower number = shows first', verbose_name='Display Order'),
        ),
    ]
