# Generated by Django 4.2.11 on 2026-01-10 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0023_alter_courselearningoutcome_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='FAQ Question', max_length=255)),
                ('answer', models.TextField(help_text='Detailed answer shown when expanded')),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls FAQ order')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='yume_site.course')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'Frequently Asked Questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseCertificationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Example: Resume Building Workshop', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_points', to='yume_site.course')),
            ],
            options={
                'verbose_name': 'Certification / Placement Point',
                'verbose_name_plural': 'Certification & Placement Support',
                'ordering': ['order'],
            },
        ),
    ]
