# Generated by Django 4.2.11 on 2026-01-10 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0024_coursefaq_coursecertificationpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCareerOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Example: Data Analyst', max_length=100)),
                ('subtitle', models.CharField(help_text='Example: Entry to Mid-level positions', max_length=150)),
                ('tag', models.CharField(help_text='Example: High Demand', max_length=50)),
                ('icon_class', models.CharField(help_text='Bootstrap icon class (example: bi-graph-up)', max_length=50)),
                ('color', models.CharField(choices=[('primary', 'Blue'), ('success', 'Green'), ('warning', 'Yellow'), ('info', 'Sky Blue')], default='primary', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_opportunities', to='yume_site.course')),
            ],
            options={
                'verbose_name': 'Career Opportunity',
                'verbose_name_plural': 'Career Opportunities',
                'ordering': ['order'],
            },
        ),
    ]
