# Generated by Django 4.2.11 on 2026-01-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0025_coursecareeropportunity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecareeropportunity',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='coursecareeropportunity',
            name='icon',
            field=models.CharField(choices=[('graph', '📊 Data / Graph'), ('finance', '💰 Finance'), ('business', '📈 Business'), ('speed', '⚡ Performance')], default='graph', max_length=20, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='coursecareeropportunity',
            name='color',
            field=models.CharField(choices=[('primary', 'Blue'), ('success', 'Green'), ('warning', 'Yellow'), ('info', 'Sky Blue')], default='primary', max_length=20, verbose_name='Theme Color'),
        ),
        migrations.AlterField(
            model_name='coursecareeropportunity',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower number shows first', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='coursecareeropportunity',
            name='subtitle',
            field=models.CharField(help_text='Example: Entry to Mid-level positions', max_length=150, verbose_name='Industry / Level'),
        ),
        migrations.AlterField(
            model_name='coursecareeropportunity',
            name='tag',
            field=models.CharField(help_text='Example: High Demand, Growing Field', max_length=50, verbose_name='Career Tag'),
        ),
        migrations.AlterField(
            model_name='coursecareeropportunity',
            name='title',
            field=models.CharField(help_text='Example: Data Analyst, Business Analyst', max_length=100, verbose_name='Job Role'),
        ),
    ]
