# Generated by Django 4.2.11 on 2026-01-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0026_remove_coursecareeropportunity_icon_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecareeropportunity',
            name='color',
        ),
        migrations.RemoveField(
            model_name='coursecareeropportunity',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='coursecareeropportunity',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='coursecareeropportunity',
            name='description',
            field=models.CharField(default='', help_text='Example: Entry to Mid-level positions', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursecareeropportunity',
            name='icon_type',
            field=models.CharField(choices=[('data', '📊 Data / Analytics'), ('finance', '💰 Finance / Money'), ('business', '📈 Business / Growth'), ('speed', '⚡ Performance / Speed'), ('intelligence', '🧠 Intelligence'), ('corporate', '🏢 Corporate'), ('reporting', '🧮 Reporting'), ('tech', '🖥️ IT / Technology')], default='data', help_text='Select icon type (no technical knowledge needed)', max_length=20),
        ),
        migrations.AlterField(
            model_name='coursecareeropportunity',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Controls display order (1, 2, 3...)'),
        ),
        migrations.AlterField(
            model_name='coursecareeropportunity',
            name='tag',
            field=models.CharField(help_text='Example: High Demand, Growing Field', max_length=50),
        ),
        migrations.AlterField(
            model_name='coursecareeropportunity',
            name='title',
            field=models.CharField(help_text='Example: Data Analyst', max_length=100),
        ),
    ]
