# Generated by Django 4.2.11 on 2026-01-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0027_remove_coursecareeropportunity_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecareeropportunity',
            name='description',
            field=models.TextField(help_text='Example: Entry to Mid-level positions', max_length=150),
        ),
    ]
