# Generated by Django 4.2.11 on 2026-01-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0028_alter_coursecareeropportunity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecareeropportunity',
            name='description',
            field=models.TextField(help_text='Example: Entry to Mid-level positions'),
        ),
        migrations.AlterField(
            model_name='coursecareeropportunity',
            name='icon_type',
            field=models.CharField(choices=[('data', '📊 Data / Analytics'), ('finance', '💰 Finance / Money'), ('business', '📈 Business / Growth'), ('speed', '⚡ Performance / Speed'), ('intelligence', '🧠 Intelligence'), ('corporate', '🏢 Corporate'), ('reporting', '🧮 Reporting'), ('tech', '🖥️ IT / Technology')], default='data', help_text='Just select from dropdown (no technical knowledge needed)', max_length=20),
        ),
    ]
