# Generated by Django 4.2.11 on 2026-01-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0029_alter_coursecareeropportunity_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
