# Generated by Django 4.2.11 on 2026-01-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0030_alter_project_duration_alter_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('short_description', models.TextField()),
                ('detailed_description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
