# Generated by Django 4.2.11 on 2026-01-12 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0031_dynamicproject_delete_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicproject',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='dynamicproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dynamicproject',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
