# Generated by Django 4.2.11 on 2026-01-12 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0032_alter_dynamicproject_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='Enter the project name (e.g., ASPIRE Project)', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of project name (auto-generated)', max_length=200, unique=True)),
                ('tagline', models.CharField(help_text='Short catchy phrase about the project', max_length=300)),
                ('category', models.CharField(choices=[('skill_development', '🎯 Skill Development Program'), ('government_program', '🏛️ Government Program'), ('intensive_training', '⚡ Intensive Training Program'), ('employability', '💼 Employability Program'), ('tech_training', '💻 Technology Training Program')], default='skill_development', help_text='Select project category', max_length=50)),
                ('short_description', models.TextField(help_text='Brief description for project card (max 150 characters)', max_length=150)),
                ('detailed_description', models.TextField(help_text='Full project details for the detail page')),
                ('thumbnail_image', models.ImageField(help_text='Small image for project card (300x200px recommended)', upload_to='projects/thumbnails/')),
                ('hero_image', models.ImageField(blank=True, help_text='Large image for project detail page', null=True, upload_to='projects/hero/')),
                ('duration', models.CharField(default='120 Hours', help_text='e.g., 120 Hours, 50 Hours, 1-2 Weeks', max_length=50)),
                ('student_count', models.IntegerField(default=0, help_text='Number of students in the program')),
                ('location', models.CharField(default='Bengaluru', help_text='Project location', max_length=100)),
                ('target_audience', models.TextField(blank=True, help_text='Who is this program for? (e.g., BCA & BSc students)')),
                ('show_partners_section', models.BooleanField(default=False, help_text='Show partners section on detail page')),
                ('badge_text', models.CharField(default='Skill Development Program', help_text='Badge text (e.g., Skill Development Program)', max_length=100)),
                ('launch_date', models.CharField(blank=True, default='July 2025 Launch', help_text='Launch date badge (e.g., July 2025 Launch)', max_length=100)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which projects appear (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this project on website')),
                ('featured', models.BooleanField(default=False, help_text='Highlight this project')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(help_text='Partner organization name', max_length=100)),
                ('partner_type', models.CharField(help_text='e.g., Implementing Partner, Knowledge Partner', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Partner logo (optional)', null=True, upload_to='projects/partners/')),
                ('icon_class', models.CharField(blank=True, default='bi-building', help_text='Bootstrap icon class (e.g., bi-building, bi-shield-check)', max_length=50)),
                ('icon_color', models.CharField(choices=[('primary', 'Blue'), ('success', 'Green'), ('info', 'Light Blue'), ('warning', 'Yellow'), ('danger', 'Red')], default='primary', help_text='Icon color', max_length=30)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which partners appear')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='yume_site.project')),
            ],
            options={
                'verbose_name': 'Project Partner',
                'verbose_name_plural': 'Project Partners',
                'ordering': ['display_order'],
            },
        ),
        migrations.DeleteModel(
            name='DynamicProject',
        ),
    ]
