# Generated by Django 4.2.11 on 2026-01-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0033_project_projectpartner_delete_dynamicproject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='badge_text',
        ),
        migrations.RemoveField(
            model_name='project',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='project',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='project',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='launch_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='show_partners_section',
        ),
        migrations.RemoveField(
            model_name='project',
            name='student_count',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='project',
            name='thumbnail_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='projects/default_project.jpg', help_text='Main project image (recommended size: 1200x800)', upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='launch_info',
            field=models.CharField(default='', help_text='Example: July 2025 Launch', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='students',
            field=models.CharField(default='', help_text='Example: 300+', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='', help_text='Project name shown on website', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(help_text='Example: Skill Development Program', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='detailed_description',
            field=models.TextField(help_text='Full description shown on detailed page'),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.CharField(help_text='Example: 120 Hours', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this project from website'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(help_text='Example: Bengaluru', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.TextField(help_text='Short description shown on project card'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_audience',
            field=models.TextField(help_text='Who is this project for?'),
        ),
        migrations.DeleteModel(
            name='ProjectPartner',
        ),
    ]
