# Generated by Django 4.2.11 on 2026-01-13 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0035_alter_project_image_alter_project_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='Enter the project name (e.g., ASPIRE Project)', max_length=200)),
                ('tagline', models.CharField(help_text='Short catchy phrase about the project', max_length=300)),
                ('category', models.CharField(help_text='e.g., Technology Training, Government Program', max_length=100)),
                ('duration', models.CharField(help_text='e.g., 120 Hours, 50 Hours, 1-2 Weeks', max_length=50)),
                ('short_description', models.TextField(help_text='Brief description for project card (max 150 characters)', max_length=150)),
                ('thumbnail_image', models.ImageField(help_text='Image for project card (300x200px recommended)', upload_to='projects/card_images/')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which projects appear (0 = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this project card on website')),
                ('featured', models.BooleanField(default=False, help_text='Highlight this project')),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated URL', max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Card',
                'verbose_name_plural': 'Project Cards',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Skill Development Program', help_text='Badge text in header (e.g., Skill Development Program)', max_length=100)),
                ('launch_date_badge', models.CharField(blank=True, default='July 2025 Launch', help_text='Launch date badge (e.g., July 2025 Launch)', max_length=100)),
                ('duration_hours', models.CharField(default='120 Hours', help_text='Duration for metrics section', max_length=50)),
                ('student_count', models.IntegerField(default=300, help_text='Number of students for metrics')),
                ('location', models.CharField(default='Bengaluru', help_text='Location for metrics', max_length=100)),
                ('target_audience', models.TextField(blank=True, help_text='Target audience description')),
                ('hero_image', models.ImageField(blank=True, help_text='Large image for project detail page', upload_to='projects/hero_images/')),
                ('show_partners', models.BooleanField(default=True, help_text='Show partners section on detail page')),
                ('partner_1_name', models.CharField(blank=True, default='YuMe Learning', help_text='First partner name', max_length=100)),
                ('partner_1_type', models.CharField(blank=True, default='Implementing Partner', help_text='First partner type', max_length=100)),
                ('partner_1_icon', models.CharField(blank=True, default='bi-building', help_text='Icon class for first partner', max_length=50)),
                ('partner_1_color', models.CharField(blank=True, default='primary', help_text='Color for first partner', max_length=30)),
                ('partner_2_name', models.CharField(blank=True, default='NASSCOM', help_text='Second partner name', max_length=100)),
                ('partner_2_type', models.CharField(blank=True, default='Knowledge Partner', help_text='Second partner type', max_length=100)),
                ('partner_2_icon', models.CharField(blank=True, default='bi-shield-check', help_text='Icon class for second partner', max_length=50)),
                ('partner_2_color', models.CharField(blank=True, default='success', help_text='Color for second partner', max_length=30)),
                ('partner_3_name', models.CharField(blank=True, default='ITC', help_text='Third partner name', max_length=100)),
                ('partner_3_type', models.CharField(blank=True, default='CSR Partner', help_text='Third partner type', max_length=100)),
                ('partner_3_icon', models.CharField(blank=True, default='fa-handshake', help_text='Icon class for third partner', max_length=50)),
                ('partner_3_color', models.CharField(blank=True, default='info', help_text='Color for third partner', max_length=30)),
                ('detailed_content', models.TextField(blank=True, help_text='Full project details for the detail page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_card', models.OneToOneField(help_text='Select the project card this detail page belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='detail_page', to='yume_site.projectcard')),
            ],
            options={
                'verbose_name': 'Project Detail Page',
                'verbose_name_plural': 'Project Detail Pages',
            },
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
