# Generated by Django 4.2.11 on 2026-01-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0036_projectcard_projectdetail_delete_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcard',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='projectdetail',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='projectdetail',
            name='partner_1_color',
        ),
        migrations.RemoveField(
            model_name='projectdetail',
            name='partner_1_icon',
        ),
        migrations.RemoveField(
            model_name='projectdetail',
            name='partner_2_color',
        ),
        migrations.RemoveField(
            model_name='projectdetail',
            name='partner_2_icon',
        ),
        migrations.RemoveField(
            model_name='projectdetail',
            name='partner_3_color',
        ),
        migrations.RemoveField(
            model_name='projectdetail',
            name='partner_3_icon',
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order in which projects appear (0 = first, 1 = second, etc.)'),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='short_description',
            field=models.TextField(help_text='Brief description for project card', max_length=150),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='badge_text',
            field=models.CharField(default='Skill Development Program', help_text='Badge text in header', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='launch_date_badge',
            field=models.CharField(blank=True, default='July 2025 Launch', help_text='Launch date badge', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='partner_1_name',
            field=models.CharField(blank=True, default='YuMe Learning', help_text='First partner organization name', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='partner_1_type',
            field=models.CharField(blank=True, default='Implementing Partner', help_text='First partner type/role', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='partner_2_name',
            field=models.CharField(blank=True, default='NASSCOM', help_text='Second partner organization name', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='partner_2_type',
            field=models.CharField(blank=True, default='Knowledge Partner', help_text='Second partner type/role', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='partner_3_name',
            field=models.CharField(blank=True, default='ITC', help_text='Third partner organization name', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='partner_3_type',
            field=models.CharField(blank=True, default='CSR Partner', help_text='Third partner type/role', max_length=100),
        ),
    ]
