# Generated by Django 4.2.11 on 2026-01-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0037_remove_projectcard_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Large image for project detail page (optional - uses card image if empty)', null=True, upload_to='projects/hero_images/'),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='partner_1_color',
            field=models.CharField(choices=[('primary', '🔵 Blue (Primary)'), ('success', '🟢 Green (Success)'), ('info', '🔵 Light Blue (Info)'), ('warning', '🟡 Yellow (Warning)'), ('danger', '🔴 Red (Danger)'), ('secondary', '⚫ Gray (Secondary)')], default='primary', help_text='Select color for first partner', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='partner_1_icon',
            field=models.CharField(choices=[('bi-building', '🏢 Building (Organization)'), ('bi-shield-check', '🛡️ Shield (Security/Knowledge)'), ('bi-handshake', '🤝 Handshake (Partnership)'), ('bi-people', '👥 People (Team/Community)'), ('bi-briefcase', '💼 Briefcase (Business)'), ('bi-lightbulb', '💡 Lightbulb (Innovation)'), ('bi-graph-up', '📈 Graph (Growth)'), ('bi-award', '🏆 Award (Excellence)'), ('bi-globe', '🌐 Globe (Global/Network)'), ('bi-cash-coin', '💰 Money (Funding/CSR)'), ('bi-book', '📚 Book (Knowledge/Education)'), ('bi-gear', '⚙️ Gear (Technology)'), ('bi-heart', '❤️ Heart (Social/CSR)'), ('bi-star', '⭐ Star (Quality/Excellence)'), ('bi-flag', '🚩 Flag (Government/Initiative)')], default='bi-building', help_text='Select an icon for first partner', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='partner_2_color',
            field=models.CharField(choices=[('primary', '🔵 Blue (Primary)'), ('success', '🟢 Green (Success)'), ('info', '🔵 Light Blue (Info)'), ('warning', '🟡 Yellow (Warning)'), ('danger', '🔴 Red (Danger)'), ('secondary', '⚫ Gray (Secondary)')], default='success', help_text='Select color for second partner', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='partner_2_icon',
            field=models.CharField(choices=[('bi-building', '🏢 Building (Organization)'), ('bi-shield-check', '🛡️ Shield (Security/Knowledge)'), ('bi-handshake', '🤝 Handshake (Partnership)'), ('bi-people', '👥 People (Team/Community)'), ('bi-briefcase', '💼 Briefcase (Business)'), ('bi-lightbulb', '💡 Lightbulb (Innovation)'), ('bi-graph-up', '📈 Graph (Growth)'), ('bi-award', '🏆 Award (Excellence)'), ('bi-globe', '🌐 Globe (Global/Network)'), ('bi-cash-coin', '💰 Money (Funding/CSR)'), ('bi-book', '📚 Book (Knowledge/Education)'), ('bi-gear', '⚙️ Gear (Technology)'), ('bi-heart', '❤️ Heart (Social/CSR)'), ('bi-star', '⭐ Star (Quality/Excellence)'), ('bi-flag', '🚩 Flag (Government/Initiative)')], default='bi-shield-check', help_text='Select an icon for second partner', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='partner_3_color',
            field=models.CharField(choices=[('primary', '🔵 Blue (Primary)'), ('success', '🟢 Green (Success)'), ('info', '🔵 Light Blue (Info)'), ('warning', '🟡 Yellow (Warning)'), ('danger', '🔴 Red (Danger)'), ('secondary', '⚫ Gray (Secondary)')], default='info', help_text='Select color for third partner', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='partner_3_icon',
            field=models.CharField(choices=[('bi-building', '🏢 Building (Organization)'), ('bi-shield-check', '🛡️ Shield (Security/Knowledge)'), ('bi-handshake', '🤝 Handshake (Partnership)'), ('bi-people', '👥 People (Team/Community)'), ('bi-briefcase', '💼 Briefcase (Business)'), ('bi-lightbulb', '💡 Lightbulb (Innovation)'), ('bi-graph-up', '📈 Graph (Growth)'), ('bi-award', '🏆 Award (Excellence)'), ('bi-globe', '🌐 Globe (Global/Network)'), ('bi-cash-coin', '💰 Money (Funding/CSR)'), ('bi-book', '📚 Book (Knowledge/Education)'), ('bi-gear', '⚙️ Gear (Technology)'), ('bi-heart', '❤️ Heart (Social/CSR)'), ('bi-star', '⭐ Star (Quality/Excellence)'), ('bi-flag', '🚩 Flag (Government/Initiative)')], default='bi-handshake', help_text='Select an icon for third partner', max_length=50),
        ),
    ]
