# Generated by Django 4.2.11 on 2026-01-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0038_projectdetail_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='implementing_partner_name',
            field=models.CharField(blank=True, default='YuMe Learning', help_text='Name of implementing partner', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='learning_approach_icon',
            field=models.CharField(choices=[('bi-building', '🏢 Building (Organization)'), ('bi-shield-check', '🛡️ Shield (Security/Knowledge)'), ('bi-handshake', '🤝 Handshake (Partnership)'), ('bi-people', '👥 People (Team/Community)'), ('bi-briefcase', '💼 Briefcase (Business)'), ('bi-lightbulb', '💡 Lightbulb (Innovation)'), ('bi-graph-up', '📈 Graph (Growth)'), ('bi-award', '🏆 Award (Excellence)'), ('bi-globe', '🌐 Globe (Global/Network)'), ('bi-cash-coin', '💰 Money (Funding/CSR)'), ('bi-book', '📚 Book (Knowledge/Education)'), ('bi-gear', '⚙️ Gear (Technology)'), ('bi-heart', '❤️ Heart (Social/CSR)'), ('bi-star', '⭐ Star (Quality/Excellence)'), ('bi-flag', '🚩 Flag (Government/Initiative)')], default='bi-person-video3', help_text='Icon for learning approach box', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='learning_approach_main',
            field=models.CharField(blank=True, default='Primarily In-person sessions', help_text='Main learning approach text', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='learning_approach_sub',
            field=models.CharField(blank=True, default='with occasional online support', help_text='Subtext for learning approach', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='learning_approach_title',
            field=models.CharField(blank=True, default='Learning Approach', help_text='Title for learning approach box', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='partner_2_name_overview',
            field=models.CharField(blank=True, default='NASSCOM Foundation', help_text='Name of second partner', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='partner_3_name_overview',
            field=models.CharField(blank=True, default='ITC', help_text='Name of third partner', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='program_objective',
            field=models.TextField(blank=True, help_text='Program objective/description'),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='program_overview_content',
            field=models.TextField(blank=True, help_text='Main content for program overview section'),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='program_overview_title',
            field=models.CharField(blank=True, default='Program Overview', help_text='Title for program overview section', max_length=200),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='show_program_overview',
            field=models.BooleanField(default=True, help_text='Show program overview section'),
        ),
    ]
