# Generated by Django 4.2.11 on 2026-01-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0039_projectdetail_implementing_partner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='component_1_color',
            field=models.CharField(choices=[('primary', '🔵 Blue (Primary)'), ('success', '🟢 Green (Success)'), ('info', '🔵 Light Blue (Info)'), ('warning', '🟡 Yellow (Warning)'), ('danger', '🔴 Red (Danger)'), ('secondary', '⚫ Gray (Secondary)')], default='primary', help_text='Color for first component', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='component_1_icon',
            field=models.CharField(choices=[('bi-building', '🏢 Building (Organization)'), ('bi-shield-check', '🛡️ Shield (Security/Knowledge)'), ('bi-handshake', '🤝 Handshake (Partnership)'), ('bi-people', '👥 People (Team/Community)'), ('bi-briefcase', '💼 Briefcase (Business)'), ('bi-lightbulb', '💡 Lightbulb (Innovation)'), ('bi-graph-up', '📈 Graph (Growth)'), ('bi-award', '🏆 Award (Excellence)'), ('bi-globe', '🌐 Globe (Global/Network)'), ('bi-cash-coin', '💰 Money (Funding/CSR)'), ('bi-book', '📚 Book (Knowledge/Education)'), ('bi-gear', '⚙️ Gear (Technology)'), ('bi-heart', '❤️ Heart (Social/CSR)'), ('bi-star', '⭐ Star (Quality/Excellence)'), ('bi-flag', '🚩 Flag (Government/Initiative)')], default='bi-code-slash', help_text='Icon for first component', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='component_1_items',
            field=models.TextField(blank=True, default='Python Programming\nFull Stack Development\nData Analytics\nSQL Database Management\nReal Dataset Problem-solving', help_text='List items for first component (one per line)'),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='component_1_subtitle',
            field=models.CharField(blank=True, default='Programming & Development', help_text='Subtitle for first component', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='component_1_title',
            field=models.CharField(blank=True, default='Technical Skills', help_text='Title for first component', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='component_2_color',
            field=models.CharField(choices=[('primary', '🔵 Blue (Primary)'), ('success', '🟢 Green (Success)'), ('info', '🔵 Light Blue (Info)'), ('warning', '🟡 Yellow (Warning)'), ('danger', '🔴 Red (Danger)'), ('secondary', '⚫ Gray (Secondary)')], default='success', help_text='Color for second component', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='component_2_icon',
            field=models.CharField(choices=[('bi-building', '🏢 Building (Organization)'), ('bi-shield-check', '🛡️ Shield (Security/Knowledge)'), ('bi-handshake', '🤝 Handshake (Partnership)'), ('bi-people', '👥 People (Team/Community)'), ('bi-briefcase', '💼 Briefcase (Business)'), ('bi-lightbulb', '💡 Lightbulb (Innovation)'), ('bi-graph-up', '📈 Graph (Growth)'), ('bi-award', '🏆 Award (Excellence)'), ('bi-globe', '🌐 Globe (Global/Network)'), ('bi-cash-coin', '💰 Money (Funding/CSR)'), ('bi-book', '📚 Book (Knowledge/Education)'), ('bi-gear', '⚙️ Gear (Technology)'), ('bi-heart', '❤️ Heart (Social/CSR)'), ('bi-star', '⭐ Star (Quality/Excellence)'), ('bi-flag', '🚩 Flag (Government/Initiative)')], default='bi-laptop', help_text='Icon for second component', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='component_2_items',
            field=models.TextField(blank=True, default='Weekly Lab Sessions\nIndustry Mini-Projects\nCapstone Project\nTeam-based Simulations\nContinuous Assessment', help_text='List items for second component (one per line)'),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='component_2_subtitle',
            field=models.CharField(blank=True, default='Practical Experience', help_text='Subtitle for second component', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='component_2_title',
            field=models.CharField(blank=True, default='Hands-on Projects', help_text='Title for second component', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='component_3_color',
            field=models.CharField(choices=[('primary', '🔵 Blue (Primary)'), ('success', '🟢 Green (Success)'), ('info', '🔵 Light Blue (Info)'), ('warning', '🟡 Yellow (Warning)'), ('danger', '🔴 Red (Danger)'), ('secondary', '⚫ Gray (Secondary)')], default='warning', help_text='Color for third component', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='component_3_icon',
            field=models.CharField(choices=[('bi-building', '🏢 Building (Organization)'), ('bi-shield-check', '🛡️ Shield (Security/Knowledge)'), ('bi-handshake', '🤝 Handshake (Partnership)'), ('bi-people', '👥 People (Team/Community)'), ('bi-briefcase', '💼 Briefcase (Business)'), ('bi-lightbulb', '💡 Lightbulb (Innovation)'), ('bi-graph-up', '📈 Graph (Growth)'), ('bi-award', '🏆 Award (Excellence)'), ('bi-globe', '🌐 Globe (Global/Network)'), ('bi-cash-coin', '💰 Money (Funding/CSR)'), ('bi-book', '📚 Book (Knowledge/Education)'), ('bi-gear', '⚙️ Gear (Technology)'), ('bi-heart', '❤️ Heart (Social/CSR)'), ('bi-star', '⭐ Star (Quality/Excellence)'), ('bi-flag', '🚩 Flag (Government/Initiative)')], default='bi-briefcase', help_text='Icon for third component', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='component_3_items',
            field=models.TextField(blank=True, default='Resume & Portfolio Building\nLinkedIn Optimization\nMock Interview Sessions\nProfessional Communication\nIndustry Networking', help_text='List items for third component (one per line)'),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='component_3_subtitle',
            field=models.CharField(blank=True, default='Professional Development', help_text='Subtitle for third component', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='component_3_title',
            field=models.CharField(blank=True, default='Career Readiness', help_text='Title for third component', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='components_title',
            field=models.CharField(blank=True, default='Core Program Components', help_text='Title for program components section', max_length=200),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='show_program_components',
            field=models.BooleanField(default=True, help_text='Show core program components section'),
        ),
    ]
