# Generated by Django 4.2.11 on 2026-01-13 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0040_projectdetail_component_1_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='impact_main_number',
            field=models.CharField(blank=True, default='2,500+', help_text='Main impact number', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='impact_main_text',
            field=models.CharField(blank=True, default='Students Trained', help_text='Text for main impact number', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='impact_metric_1_number',
            field=models.CharField(blank=True, default='5+', help_text='First impact metric number', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='impact_metric_1_text',
            field=models.CharField(blank=True, default='Regions', help_text='First impact metric text', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='impact_metric_2_number',
            field=models.CharField(blank=True, default='50', help_text='Second impact metric number', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='impact_metric_2_text',
            field=models.CharField(blank=True, default='Hours/Student', help_text='Second impact metric text', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='impact_title',
            field=models.CharField(blank=True, default='Program Impact', help_text='Title for impact section', max_length=200),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='outcome_1_color',
            field=models.CharField(choices=[('primary', '🔵 Blue (Primary)'), ('success', '🟢 Green (Success)'), ('info', '🔵 Light Blue (Info)'), ('warning', '🟡 Yellow (Warning)'), ('danger', '🔴 Red (Danger)'), ('secondary', '⚫ Gray (Secondary)')], default='success', help_text='Color for first outcome progress bar', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='outcome_1_label',
            field=models.CharField(blank=True, default='Skill Enhancement', help_text='First outcome label', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='outcome_1_value',
            field=models.IntegerField(default=94, help_text='First outcome percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='outcome_2_color',
            field=models.CharField(choices=[('primary', '🔵 Blue (Primary)'), ('success', '🟢 Green (Success)'), ('info', '🔵 Light Blue (Info)'), ('warning', '🟡 Yellow (Warning)'), ('danger', '🔴 Red (Danger)'), ('secondary', '⚫ Gray (Secondary)')], default='warning', help_text='Color for second outcome progress bar', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='outcome_2_label',
            field=models.CharField(blank=True, default='Employability', help_text='Second outcome label', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='outcome_2_value',
            field=models.IntegerField(default=89, help_text='Second outcome percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='outcome_3_color',
            field=models.CharField(choices=[('primary', '🔵 Blue (Primary)'), ('success', '🟢 Green (Success)'), ('info', '🔵 Light Blue (Info)'), ('warning', '🟡 Yellow (Warning)'), ('danger', '🔴 Red (Danger)'), ('secondary', '⚫ Gray (Secondary)')], default='info', help_text='Color for third outcome progress bar', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='outcome_3_label',
            field=models.CharField(blank=True, default='Student Satisfaction', help_text='Third outcome label', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='outcome_3_value',
            field=models.IntegerField(default=96, help_text='Third outcome percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='role_description',
            field=models.TextField(blank=True, default='As the implementing partner, YuMe Learning is responsible for comprehensive program delivery and outcome measurement across multiple regions in Karnataka.', help_text='Description of implementing partner role'),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='role_item_1_color',
            field=models.CharField(choices=[('primary', '🔵 Blue (Primary)'), ('success', '🟢 Green (Success)'), ('info', '🔵 Light Blue (Info)'), ('warning', '🟡 Yellow (Warning)'), ('danger', '🔴 Red (Danger)'), ('secondary', '⚫ Gray (Secondary)')], default='primary', help_text='Color for first role item', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='role_item_1_icon',
            field=models.CharField(choices=[('bi-building', '🏢 Building (Organization)'), ('bi-shield-check', '🛡️ Shield (Security/Knowledge)'), ('bi-handshake', '🤝 Handshake (Partnership)'), ('bi-people', '👥 People (Team/Community)'), ('bi-briefcase', '💼 Briefcase (Business)'), ('bi-lightbulb', '💡 Lightbulb (Innovation)'), ('bi-graph-up', '📈 Graph (Growth)'), ('bi-award', '🏆 Award (Excellence)'), ('bi-globe', '🌐 Globe (Global/Network)'), ('bi-cash-coin', '💰 Money (Funding/CSR)'), ('bi-book', '📚 Book (Knowledge/Education)'), ('bi-gear', '⚙️ Gear (Technology)'), ('bi-heart', '❤️ Heart (Social/CSR)'), ('bi-star', '⭐ Star (Quality/Excellence)'), ('bi-flag', '🚩 Flag (Government/Initiative)')], default='bi-gear', help_text='Icon for first role item', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='role_item_1_subtitle',
            field=models.CharField(blank=True, default='Training execution & management', help_text='First role item subtitle', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='role_item_1_title',
            field=models.CharField(blank=True, default='Program Delivery', help_text='First role item title', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='role_item_2_color',
            field=models.CharField(choices=[('primary', '🔵 Blue (Primary)'), ('success', '🟢 Green (Success)'), ('info', '🔵 Light Blue (Info)'), ('warning', '🟡 Yellow (Warning)'), ('danger', '🔴 Red (Danger)'), ('secondary', '⚫ Gray (Secondary)')], default='success', help_text='Color for second role item', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='role_item_2_icon',
            field=models.CharField(choices=[('bi-building', '🏢 Building (Organization)'), ('bi-shield-check', '🛡️ Shield (Security/Knowledge)'), ('bi-handshake', '🤝 Handshake (Partnership)'), ('bi-people', '👥 People (Team/Community)'), ('bi-briefcase', '💼 Briefcase (Business)'), ('bi-lightbulb', '💡 Lightbulb (Innovation)'), ('bi-graph-up', '📈 Graph (Growth)'), ('bi-award', '🏆 Award (Excellence)'), ('bi-globe', '🌐 Globe (Global/Network)'), ('bi-cash-coin', '💰 Money (Funding/CSR)'), ('bi-book', '📚 Book (Knowledge/Education)'), ('bi-gear', '⚙️ Gear (Technology)'), ('bi-heart', '❤️ Heart (Social/CSR)'), ('bi-star', '⭐ Star (Quality/Excellence)'), ('bi-flag', '🚩 Flag (Government/Initiative)')], default='bi-people', help_text='Icon for second role item', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='role_item_2_subtitle',
            field=models.CharField(blank=True, default='Student support & monitoring', help_text='Second role item subtitle', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='role_item_2_title',
            field=models.CharField(blank=True, default='Learner Engagement', help_text='Second role item title', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='role_item_3_color',
            field=models.CharField(choices=[('primary', '🔵 Blue (Primary)'), ('success', '🟢 Green (Success)'), ('info', '🔵 Light Blue (Info)'), ('warning', '🟡 Yellow (Warning)'), ('danger', '🔴 Red (Danger)'), ('secondary', '⚫ Gray (Secondary)')], default='info', help_text='Color for third role item', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='role_item_3_icon',
            field=models.CharField(choices=[('bi-building', '🏢 Building (Organization)'), ('bi-shield-check', '🛡️ Shield (Security/Knowledge)'), ('bi-handshake', '🤝 Handshake (Partnership)'), ('bi-people', '👥 People (Team/Community)'), ('bi-briefcase', '💼 Briefcase (Business)'), ('bi-lightbulb', '💡 Lightbulb (Innovation)'), ('bi-graph-up', '📈 Graph (Growth)'), ('bi-award', '🏆 Award (Excellence)'), ('bi-globe', '🌐 Globe (Global/Network)'), ('bi-cash-coin', '💰 Money (Funding/CSR)'), ('bi-book', '📚 Book (Knowledge/Education)'), ('bi-gear', '⚙️ Gear (Technology)'), ('bi-heart', '❤️ Heart (Social/CSR)'), ('bi-star', '⭐ Star (Quality/Excellence)'), ('bi-flag', '🚩 Flag (Government/Initiative)')], default='bi-graph-up', help_text='Icon for third role item', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='role_item_3_subtitle',
            field=models.CharField(blank=True, default='Impact assessment & reporting', help_text='Third role item subtitle', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='role_item_3_title',
            field=models.CharField(blank=True, default='Outcome Measurement', help_text='Third role item title', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='role_item_4_color',
            field=models.CharField(choices=[('primary', '🔵 Blue (Primary)'), ('success', '🟢 Green (Success)'), ('info', '🔵 Light Blue (Info)'), ('warning', '🟡 Yellow (Warning)'), ('danger', '🔴 Red (Danger)'), ('secondary', '⚫ Gray (Secondary)')], default='warning', help_text='Color for fourth role item', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='role_item_4_icon',
            field=models.CharField(choices=[('bi-building', '🏢 Building (Organization)'), ('bi-shield-check', '🛡️ Shield (Security/Knowledge)'), ('bi-handshake', '🤝 Handshake (Partnership)'), ('bi-people', '👥 People (Team/Community)'), ('bi-briefcase', '💼 Briefcase (Business)'), ('bi-lightbulb', '💡 Lightbulb (Innovation)'), ('bi-graph-up', '📈 Graph (Growth)'), ('bi-award', '🏆 Award (Excellence)'), ('bi-globe', '🌐 Globe (Global/Network)'), ('bi-cash-coin', '💰 Money (Funding/CSR)'), ('bi-book', '📚 Book (Knowledge/Education)'), ('bi-gear', '⚙️ Gear (Technology)'), ('bi-heart', '❤️ Heart (Social/CSR)'), ('bi-star', '⭐ Star (Quality/Excellence)'), ('bi-flag', '🚩 Flag (Government/Initiative)')], default='bi-geo-alt', help_text='Icon for fourth role item', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='role_item_4_subtitle',
            field=models.CharField(blank=True, default='Statewide program coverage', help_text='Fourth role item subtitle', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='role_item_4_title',
            field=models.CharField(blank=True, default='Multi-region Implementation', help_text='Fourth role item title', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='role_title',
            field=models.CharField(blank=True, default='Role of YuMe Learning', help_text='Title for role section', max_length=200),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='show_role_impact',
            field=models.BooleanField(default=True, help_text='Show role and impact section'),
        ),
    ]
