# Generated by Django 4.2.11 on 2026-01-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0041_projectdetail_impact_main_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='cert_feature_1_color',
            field=models.CharField(choices=[('primary', '🔵 Blue (Primary)'), ('success', '🟢 Green (Success)'), ('info', '🔵 Light Blue (Info)'), ('warning', '🟡 Yellow (Warning)'), ('danger', '🔴 Red (Danger)'), ('secondary', '⚫ Gray (Secondary)')], default='success', help_text='Color for first feature', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='cert_feature_1_icon',
            field=models.CharField(choices=[('bi-building', '🏢 Building (Organization)'), ('bi-shield-check', '🛡️ Shield (Security/Knowledge)'), ('bi-handshake', '🤝 Handshake (Partnership)'), ('bi-people', '👥 People (Team/Community)'), ('bi-briefcase', '💼 Briefcase (Business)'), ('bi-lightbulb', '💡 Lightbulb (Innovation)'), ('bi-graph-up', '📈 Graph (Growth)'), ('bi-award', '🏆 Award (Excellence)'), ('bi-globe', '🌐 Globe (Global/Network)'), ('bi-cash-coin', '💰 Money (Funding/CSR)'), ('bi-book', '📚 Book (Knowledge/Education)'), ('bi-gear', '⚙️ Gear (Technology)'), ('bi-heart', '❤️ Heart (Social/CSR)'), ('bi-star', '⭐ Star (Quality/Excellence)'), ('bi-flag', '🚩 Flag (Government/Initiative)')], default='bi-check-circle', help_text='Icon for first feature', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='cert_feature_1_text',
            field=models.CharField(blank=True, default='Technical Validation', help_text='First certification feature', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='cert_feature_2_color',
            field=models.CharField(choices=[('primary', '🔵 Blue (Primary)'), ('success', '🟢 Green (Success)'), ('info', '🔵 Light Blue (Info)'), ('warning', '🟡 Yellow (Warning)'), ('danger', '🔴 Red (Danger)'), ('secondary', '⚫ Gray (Secondary)')], default='primary', help_text='Color for second feature', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='cert_feature_2_icon',
            field=models.CharField(choices=[('bi-building', '🏢 Building (Organization)'), ('bi-shield-check', '🛡️ Shield (Security/Knowledge)'), ('bi-handshake', '🤝 Handshake (Partnership)'), ('bi-people', '👥 People (Team/Community)'), ('bi-briefcase', '💼 Briefcase (Business)'), ('bi-lightbulb', '💡 Lightbulb (Innovation)'), ('bi-graph-up', '📈 Graph (Growth)'), ('bi-award', '🏆 Award (Excellence)'), ('bi-globe', '🌐 Globe (Global/Network)'), ('bi-cash-coin', '💰 Money (Funding/CSR)'), ('bi-book', '📚 Book (Knowledge/Education)'), ('bi-gear', '⚙️ Gear (Technology)'), ('bi-heart', '❤️ Heart (Social/CSR)'), ('bi-star', '⭐ Star (Quality/Excellence)'), ('bi-flag', '🚩 Flag (Government/Initiative)')], default='bi-person-check', help_text='Icon for second feature', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='cert_feature_2_text',
            field=models.CharField(blank=True, default='Employability Proof', help_text='Second certification feature', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='cert_feature_3_color',
            field=models.CharField(choices=[('primary', '🔵 Blue (Primary)'), ('success', '🟢 Green (Success)'), ('info', '🔵 Light Blue (Info)'), ('warning', '🟡 Yellow (Warning)'), ('danger', '🔴 Red (Danger)'), ('secondary', '⚫ Gray (Secondary)')], default='warning', help_text='Color for third feature', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='cert_feature_3_icon',
            field=models.CharField(choices=[('bi-building', '🏢 Building (Organization)'), ('bi-shield-check', '🛡️ Shield (Security/Knowledge)'), ('bi-handshake', '🤝 Handshake (Partnership)'), ('bi-people', '👥 People (Team/Community)'), ('bi-briefcase', '💼 Briefcase (Business)'), ('bi-lightbulb', '💡 Lightbulb (Innovation)'), ('bi-graph-up', '📈 Graph (Growth)'), ('bi-award', '🏆 Award (Excellence)'), ('bi-globe', '🌐 Globe (Global/Network)'), ('bi-cash-coin', '💰 Money (Funding/CSR)'), ('bi-book', '📚 Book (Knowledge/Education)'), ('bi-gear', '⚙️ Gear (Technology)'), ('bi-heart', '❤️ Heart (Social/CSR)'), ('bi-star', '⭐ Star (Quality/Excellence)'), ('bi-flag', '🚩 Flag (Government/Initiative)')], default='bi-award', help_text='Icon for third feature', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='cert_feature_3_text',
            field=models.CharField(blank=True, default='Industry Recognition', help_text='Third certification feature', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='cert_feature_4_color',
            field=models.CharField(choices=[('primary', '🔵 Blue (Primary)'), ('success', '🟢 Green (Success)'), ('info', '🔵 Light Blue (Info)'), ('warning', '🟡 Yellow (Warning)'), ('danger', '🔴 Red (Danger)'), ('secondary', '⚫ Gray (Secondary)')], default='info', help_text='Color for fourth feature', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='cert_feature_4_icon',
            field=models.CharField(choices=[('bi-building', '🏢 Building (Organization)'), ('bi-shield-check', '🛡️ Shield (Security/Knowledge)'), ('bi-handshake', '🤝 Handshake (Partnership)'), ('bi-people', '👥 People (Team/Community)'), ('bi-briefcase', '💼 Briefcase (Business)'), ('bi-lightbulb', '💡 Lightbulb (Innovation)'), ('bi-graph-up', '📈 Graph (Growth)'), ('bi-award', '🏆 Award (Excellence)'), ('bi-globe', '🌐 Globe (Global/Network)'), ('bi-cash-coin', '💰 Money (Funding/CSR)'), ('bi-book', '📚 Book (Knowledge/Education)'), ('bi-gear', '⚙️ Gear (Technology)'), ('bi-heart', '❤️ Heart (Social/CSR)'), ('bi-star', '⭐ Star (Quality/Excellence)'), ('bi-flag', '🚩 Flag (Government/Initiative)')], default='bi-briefcase', help_text='Icon for fourth feature', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='cert_feature_4_text',
            field=models.CharField(blank=True, default='Career Readiness Support', help_text='Fourth certification feature', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='certification_color',
            field=models.CharField(choices=[('primary', '🔵 Blue (Primary)'), ('success', '🟢 Green (Success)'), ('info', '🔵 Light Blue (Info)'), ('warning', '🟡 Yellow (Warning)'), ('danger', '🔴 Red (Danger)'), ('secondary', '⚫ Gray (Secondary)')], default='primary', help_text='Color for certification card', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='certification_description',
            field=models.TextField(blank=True, default='Industry-recognized certification validating technical competencies and employability skills.', help_text='Description for certification card'),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='certification_icon',
            field=models.CharField(choices=[('bi-building', '🏢 Building (Organization)'), ('bi-shield-check', '🛡️ Shield (Security/Knowledge)'), ('bi-handshake', '🤝 Handshake (Partnership)'), ('bi-people', '👥 People (Team/Community)'), ('bi-briefcase', '💼 Briefcase (Business)'), ('bi-lightbulb', '💡 Lightbulb (Innovation)'), ('bi-graph-up', '📈 Graph (Growth)'), ('bi-award', '🏆 Award (Excellence)'), ('bi-globe', '🌐 Globe (Global/Network)'), ('bi-cash-coin', '💰 Money (Funding/CSR)'), ('bi-book', '📚 Book (Knowledge/Education)'), ('bi-gear', '⚙️ Gear (Technology)'), ('bi-heart', '❤️ Heart (Social/CSR)'), ('bi-star', '⭐ Star (Quality/Excellence)'), ('bi-flag', '🚩 Flag (Government/Initiative)')], default='bi-award', help_text='Icon for certification card', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='certification_subtitle',
            field=models.CharField(blank=True, default='Validated by NASSCOM Foundation', help_text='Subtitle for certification card', max_length=200),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='certification_title',
            field=models.CharField(blank=True, default='Industry Certification', help_text='Title for certification card', max_length=200),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='show_certification_support',
            field=models.BooleanField(default=True, help_text='Show certification and support section'),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='support_color',
            field=models.CharField(choices=[('primary', '🔵 Blue (Primary)'), ('success', '🟢 Green (Success)'), ('info', '🔵 Light Blue (Info)'), ('warning', '🟡 Yellow (Warning)'), ('danger', '🔴 Red (Danger)'), ('secondary', '⚫ Gray (Secondary)')], default='success', help_text='Color for support card', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='support_description',
            field=models.TextField(blank=True, default='Comprehensive placement and internship support with industry connections.', help_text='Description for support card'),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='support_feature_1_color',
            field=models.CharField(choices=[('primary', '🔵 Blue (Primary)'), ('success', '🟢 Green (Success)'), ('info', '🔵 Light Blue (Info)'), ('warning', '🟡 Yellow (Warning)'), ('danger', '🔴 Red (Danger)'), ('secondary', '⚫ Gray (Secondary)')], default='info', help_text='Color for first feature', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='support_feature_1_icon',
            field=models.CharField(choices=[('bi-building', '🏢 Building (Organization)'), ('bi-shield-check', '🛡️ Shield (Security/Knowledge)'), ('bi-handshake', '🤝 Handshake (Partnership)'), ('bi-people', '👥 People (Team/Community)'), ('bi-briefcase', '💼 Briefcase (Business)'), ('bi-lightbulb', '💡 Lightbulb (Innovation)'), ('bi-graph-up', '📈 Graph (Growth)'), ('bi-award', '🏆 Award (Excellence)'), ('bi-globe', '🌐 Globe (Global/Network)'), ('bi-cash-coin', '💰 Money (Funding/CSR)'), ('bi-book', '📚 Book (Knowledge/Education)'), ('bi-gear', '⚙️ Gear (Technology)'), ('bi-heart', '❤️ Heart (Social/CSR)'), ('bi-star', '⭐ Star (Quality/Excellence)'), ('bi-flag', '🚩 Flag (Government/Initiative)')], default='bi-building', help_text='Icon for first feature', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='support_feature_1_text',
            field=models.CharField(blank=True, default='Industry Connect', help_text='First support feature', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='support_feature_2_color',
            field=models.CharField(choices=[('primary', '🔵 Blue (Primary)'), ('success', '🟢 Green (Success)'), ('info', '🔵 Light Blue (Info)'), ('warning', '🟡 Yellow (Warning)'), ('danger', '🔴 Red (Danger)'), ('secondary', '⚫ Gray (Secondary)')], default='warning', help_text='Color for second feature', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='support_feature_2_icon',
            field=models.CharField(choices=[('bi-building', '🏢 Building (Organization)'), ('bi-shield-check', '🛡️ Shield (Security/Knowledge)'), ('bi-handshake', '🤝 Handshake (Partnership)'), ('bi-people', '👥 People (Team/Community)'), ('bi-briefcase', '💼 Briefcase (Business)'), ('bi-lightbulb', '💡 Lightbulb (Innovation)'), ('bi-graph-up', '📈 Graph (Growth)'), ('bi-award', '🏆 Award (Excellence)'), ('bi-globe', '🌐 Globe (Global/Network)'), ('bi-cash-coin', '💰 Money (Funding/CSR)'), ('bi-book', '📚 Book (Knowledge/Education)'), ('bi-gear', '⚙️ Gear (Technology)'), ('bi-heart', '❤️ Heart (Social/CSR)'), ('bi-star', '⭐ Star (Quality/Excellence)'), ('bi-flag', '🚩 Flag (Government/Initiative)')], default='bi-chat-dots', help_text='Icon for second feature', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='support_feature_2_text',
            field=models.CharField(blank=True, default='Mock Interviews', help_text='Second support feature', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='support_feature_3_color',
            field=models.CharField(choices=[('primary', '🔵 Blue (Primary)'), ('success', '🟢 Green (Success)'), ('info', '🔵 Light Blue (Info)'), ('warning', '🟡 Yellow (Warning)'), ('danger', '🔴 Red (Danger)'), ('secondary', '⚫ Gray (Secondary)')], default='secondary', help_text='Color for third feature', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='support_feature_3_icon',
            field=models.CharField(choices=[('bi-building', '🏢 Building (Organization)'), ('bi-shield-check', '🛡️ Shield (Security/Knowledge)'), ('bi-handshake', '🤝 Handshake (Partnership)'), ('bi-people', '👥 People (Team/Community)'), ('bi-briefcase', '💼 Briefcase (Business)'), ('bi-lightbulb', '💡 Lightbulb (Innovation)'), ('bi-graph-up', '📈 Graph (Growth)'), ('bi-award', '🏆 Award (Excellence)'), ('bi-globe', '🌐 Globe (Global/Network)'), ('bi-cash-coin', '💰 Money (Funding/CSR)'), ('bi-book', '📚 Book (Knowledge/Education)'), ('bi-gear', '⚙️ Gear (Technology)'), ('bi-heart', '❤️ Heart (Social/CSR)'), ('bi-star', '⭐ Star (Quality/Excellence)'), ('bi-flag', '🚩 Flag (Government/Initiative)')], default='bi-people', help_text='Icon for third feature', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='support_feature_3_text',
            field=models.CharField(blank=True, default='Mentorship', help_text='Third support feature', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='support_feature_4_color',
            field=models.CharField(choices=[('primary', '🔵 Blue (Primary)'), ('success', '🟢 Green (Success)'), ('info', '🔵 Light Blue (Info)'), ('warning', '🟡 Yellow (Warning)'), ('danger', '🔴 Red (Danger)'), ('secondary', '⚫ Gray (Secondary)')], default='danger', help_text='Color for fourth feature', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='support_feature_4_icon',
            field=models.CharField(choices=[('bi-building', '🏢 Building (Organization)'), ('bi-shield-check', '🛡️ Shield (Security/Knowledge)'), ('bi-handshake', '🤝 Handshake (Partnership)'), ('bi-people', '👥 People (Team/Community)'), ('bi-briefcase', '💼 Briefcase (Business)'), ('bi-lightbulb', '💡 Lightbulb (Innovation)'), ('bi-graph-up', '📈 Graph (Growth)'), ('bi-award', '🏆 Award (Excellence)'), ('bi-globe', '🌐 Globe (Global/Network)'), ('bi-cash-coin', '💰 Money (Funding/CSR)'), ('bi-book', '📚 Book (Knowledge/Education)'), ('bi-gear', '⚙️ Gear (Technology)'), ('bi-heart', '❤️ Heart (Social/CSR)'), ('bi-star', '⭐ Star (Quality/Excellence)'), ('bi-flag', '🚩 Flag (Government/Initiative)')], default='bi-graph-up', help_text='Icon for fourth feature', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='support_feature_4_text',
            field=models.CharField(blank=True, default='Career Guidance', help_text='Fourth support feature', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='support_icon',
            field=models.CharField(choices=[('bi-building', '🏢 Building (Organization)'), ('bi-shield-check', '🛡️ Shield (Security/Knowledge)'), ('bi-handshake', '🤝 Handshake (Partnership)'), ('bi-people', '👥 People (Team/Community)'), ('bi-briefcase', '💼 Briefcase (Business)'), ('bi-lightbulb', '💡 Lightbulb (Innovation)'), ('bi-graph-up', '📈 Graph (Growth)'), ('bi-award', '🏆 Award (Excellence)'), ('bi-globe', '🌐 Globe (Global/Network)'), ('bi-cash-coin', '💰 Money (Funding/CSR)'), ('bi-book', '📚 Book (Knowledge/Education)'), ('bi-gear', '⚙️ Gear (Technology)'), ('bi-heart', '❤️ Heart (Social/CSR)'), ('bi-star', '⭐ Star (Quality/Excellence)'), ('bi-flag', '🚩 Flag (Government/Initiative)')], default='bi-briefcase', help_text='Icon for support card', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='support_subtitle',
            field=models.CharField(blank=True, default='End-to-end Career Assistance', help_text='Subtitle for support card', max_length=200),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='support_title',
            field=models.CharField(blank=True, default='Placement Support', help_text='Title for support card', max_length=200),
        ),
    ]
