# Generated by Django 4.2.11 on 2026-01-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0042_projectdetail_cert_feature_1_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='highlight_1_color',
            field=models.CharField(choices=[('primary', '🔵 Blue (Primary)'), ('success', '🟢 Green (Success)'), ('info', '🔵 Light Blue (Info)'), ('warning', '🟡 Yellow (Warning)'), ('danger', '🔴 Red (Danger)'), ('secondary', '⚫ Gray (Secondary)')], default='success', help_text='Color for first highlight', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='highlight_1_text',
            field=models.CharField(blank=True, default='Industry-Aligned Curriculum', help_text='First highlight text', max_length=200),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='highlight_2_color',
            field=models.CharField(choices=[('primary', '🔵 Blue (Primary)'), ('success', '🟢 Green (Success)'), ('info', '🔵 Light Blue (Info)'), ('warning', '🟡 Yellow (Warning)'), ('danger', '🔴 Red (Danger)'), ('secondary', '⚫ Gray (Secondary)')], default='primary', help_text='Color for second highlight', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='highlight_2_text',
            field=models.CharField(blank=True, default='Hands-on Practical Experience', help_text='Second highlight text', max_length=200),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='highlight_3_color',
            field=models.CharField(choices=[('primary', '🔵 Blue (Primary)'), ('success', '🟢 Green (Success)'), ('info', '🔵 Light Blue (Info)'), ('warning', '🟡 Yellow (Warning)'), ('danger', '🔴 Red (Danger)'), ('secondary', '⚫ Gray (Secondary)')], default='warning', help_text='Color for third highlight', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='highlight_3_text',
            field=models.CharField(blank=True, default='Mentorship & Career Guidance', help_text='Third highlight text', max_length=200),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='highlights_title',
            field=models.CharField(blank=True, default='Program Highlights', help_text='Title for highlights box', max_length=200),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='partner_badge_1_color',
            field=models.CharField(choices=[('primary', '🔵 Blue (Primary)'), ('success', '🟢 Green (Success)'), ('info', '🔵 Light Blue (Info)'), ('warning', '🟡 Yellow (Warning)'), ('danger', '🔴 Red (Danger)'), ('secondary', '⚫ Gray (Secondary)')], default='primary', help_text='Color for first partner badge', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='partner_badge_1_icon',
            field=models.CharField(choices=[('bi-building', '🏢 Building (Organization)'), ('bi-shield-check', '🛡️ Shield (Security/Knowledge)'), ('bi-handshake', '🤝 Handshake (Partnership)'), ('bi-people', '👥 People (Team/Community)'), ('bi-briefcase', '💼 Briefcase (Business)'), ('bi-lightbulb', '💡 Lightbulb (Innovation)'), ('bi-graph-up', '📈 Graph (Growth)'), ('bi-award', '🏆 Award (Excellence)'), ('bi-globe', '🌐 Globe (Global/Network)'), ('bi-cash-coin', '💰 Money (Funding/CSR)'), ('bi-book', '📚 Book (Knowledge/Education)'), ('bi-gear', '⚙️ Gear (Technology)'), ('bi-heart', '❤️ Heart (Social/CSR)'), ('bi-star', '⭐ Star (Quality/Excellence)'), ('bi-flag', '🚩 Flag (Government/Initiative)')], default='bi-building', help_text='Icon for first partner badge', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='partner_badge_1_name',
            field=models.CharField(blank=True, default='YuMe Learning', help_text='First partner badge name', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='partner_badge_2_color',
            field=models.CharField(choices=[('primary', '🔵 Blue (Primary)'), ('success', '🟢 Green (Success)'), ('info', '🔵 Light Blue (Info)'), ('warning', '🟡 Yellow (Warning)'), ('danger', '🔴 Red (Danger)'), ('secondary', '⚫ Gray (Secondary)')], default='success', help_text='Color for second partner badge', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='partner_badge_2_icon',
            field=models.CharField(choices=[('bi-building', '🏢 Building (Organization)'), ('bi-shield-check', '🛡️ Shield (Security/Knowledge)'), ('bi-handshake', '🤝 Handshake (Partnership)'), ('bi-people', '👥 People (Team/Community)'), ('bi-briefcase', '💼 Briefcase (Business)'), ('bi-lightbulb', '💡 Lightbulb (Innovation)'), ('bi-graph-up', '📈 Graph (Growth)'), ('bi-award', '🏆 Award (Excellence)'), ('bi-globe', '🌐 Globe (Global/Network)'), ('bi-cash-coin', '💰 Money (Funding/CSR)'), ('bi-book', '📚 Book (Knowledge/Education)'), ('bi-gear', '⚙️ Gear (Technology)'), ('bi-heart', '❤️ Heart (Social/CSR)'), ('bi-star', '⭐ Star (Quality/Excellence)'), ('bi-flag', '🚩 Flag (Government/Initiative)')], default='bi-shield-check', help_text='Icon for second partner badge', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='partner_badge_2_name',
            field=models.CharField(blank=True, default='NASSCOM Foundation', help_text='Second partner badge name', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='partner_badge_3_color',
            field=models.CharField(choices=[('primary', '🔵 Blue (Primary)'), ('success', '🟢 Green (Success)'), ('info', '🔵 Light Blue (Info)'), ('warning', '🟡 Yellow (Warning)'), ('danger', '🔴 Red (Danger)'), ('secondary', '⚫ Gray (Secondary)')], default='info', help_text='Color for third partner badge', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='partner_badge_3_icon',
            field=models.CharField(choices=[('bi-building', '🏢 Building (Organization)'), ('bi-shield-check', '🛡️ Shield (Security/Knowledge)'), ('bi-handshake', '🤝 Handshake (Partnership)'), ('bi-people', '👥 People (Team/Community)'), ('bi-briefcase', '💼 Briefcase (Business)'), ('bi-lightbulb', '💡 Lightbulb (Innovation)'), ('bi-graph-up', '📈 Graph (Growth)'), ('bi-award', '🏆 Award (Excellence)'), ('bi-globe', '🌐 Globe (Global/Network)'), ('bi-cash-coin', '💰 Money (Funding/CSR)'), ('bi-book', '📚 Book (Knowledge/Education)'), ('bi-gear', '⚙️ Gear (Technology)'), ('bi-heart', '❤️ Heart (Social/CSR)'), ('bi-star', '⭐ Star (Quality/Excellence)'), ('bi-flag', '🚩 Flag (Government/Initiative)')], default='bi-handshake', help_text='Icon for third partner badge', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='partner_badge_3_name',
            field=models.CharField(blank=True, default='ITC', help_text='Third partner badge name', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='pathways_description',
            field=models.TextField(blank=True, default='The ASPIRE Project is more than a training program — it is a career enablement initiative. By combining technical excellence, professional skills, mentorship, and industry partnerships, YuMe Learning, along with NASSCOM Foundation and ITC, is enabling students to transition successfully from classrooms to careers.', help_text='Description for sustainable pathways section'),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='pathways_title',
            field=models.CharField(blank=True, default='Creating Sustainable Career Pathways', help_text='Title for sustainable pathways section', max_length=200),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='show_sustainable_pathways',
            field=models.BooleanField(default=True, help_text='Show sustainable pathways section'),
        ),
    ]
