# Generated by Django 4.2.11 on 2026-01-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0043_projectdetail_highlight_1_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter blog post title', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated URL', max_length=200, unique=True)),
                ('category', models.CharField(choices=[('excel', '📊 Excel'), ('sql', '🗄️ SQL'), ('python', '🐍 Python'), ('data_viz', '📈 Data Visualization'), ('azure', '☁️ Azure'), ('ai_ml', '🤖 AI & ML'), ('power_platform', '⚡ Power Platform'), ('security', '🔒 Security'), ('soft_skills', '💼 Soft Skills'), ('tech_training', '💻 Technology Training'), ('career', '🚀 Career Development')], default='tech_training', help_text='Select blog category', max_length=50)),
                ('excerpt', models.TextField(help_text='Short excerpt for blog card (max 200 chars)', max_length=200)),
                ('read_time', models.CharField(default='5 min read', help_text='e.g., 5 min read, 10 min read', max_length=50)),
                ('featured_image', models.ImageField(help_text='Featured image for blog (700x400px recommended)', upload_to='blog/featured_images/')),
                ('publish_date', models.DateField(help_text='Date when blog was published')),
                ('author_name', models.CharField(default='YuMe Learning Team', help_text='Author name', max_length=100)),
                ('author_role', models.CharField(default='Professional Development Experts', help_text='Author role/designation', max_length=100)),
                ('content', models.TextField(help_text='Full blog content')),
                ('is_published', models.BooleanField(default=True, help_text='Show this blog on website')),
                ('featured', models.BooleanField(default=False, help_text='Feature this blog')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which blogs appear (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dynamic Blog',
                'verbose_name_plural': 'Dynamic Blogs',
                'ordering': ['display_order', '-publish_date'],
            },
        ),
    ]
