# Generated by Django 4.2.11 on 2026-01-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0044_dynamicblog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicblog',
            options={'ordering': ['display_order', '-publish_date'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterField(
            model_name='dynamicblog',
            name='category',
            field=models.CharField(choices=[('excel', 'Excel'), ('sql', 'SQL'), ('python', 'Python'), ('data_viz', 'Data Visualization'), ('azure', 'Azure'), ('ai_ml', 'AI & ML'), ('power_platform', 'Power Platform'), ('security', 'Security'), ('soft_skills', 'Soft Skills'), ('tech_training', 'Technology Training'), ('career', 'Career Development')], default='tech_training', help_text='Select blog category', max_length=50),
        ),
        migrations.AlterField(
            model_name='dynamicblog',
            name='content',
            field=models.TextField(help_text='Full blog content for detail page'),
        ),
        migrations.AlterField(
            model_name='dynamicblog',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order in which blogs appear (0 = first, 1 = second)'),
        ),
        migrations.AlterField(
            model_name='dynamicblog',
            name='excerpt',
            field=models.TextField(help_text='Short description for blog card (max 200 characters)', max_length=200),
        ),
        migrations.AlterField(
            model_name='dynamicblog',
            name='featured',
            field=models.BooleanField(default=False, help_text='Feature this blog on homepage'),
        ),
        migrations.AlterField(
            model_name='dynamicblog',
            name='featured_image',
            field=models.ImageField(help_text='Image for blog card (700x400px recommended)', upload_to='blog/featured_images/'),
        ),
        migrations.AlterField(
            model_name='dynamicblog',
            name='publish_date',
            field=models.DateField(help_text='Select publish date for blog'),
        ),
        migrations.AlterField(
            model_name='dynamicblog',
            name='read_time',
            field=models.CharField(default='5 min read', help_text='Estimated reading time (e.g., 5 min read, 10 min read)', max_length=50),
        ),
        migrations.AlterField(
            model_name='dynamicblog',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
