# Generated by Django 4.2.11 on 2026-01-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0045_alter_dynamicblog_options_alter_dynamicblog_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicblog',
            name='content',
        ),
    ]
