# Generated by Django 4.2.11 on 2026-01-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0046_remove_dynamicblog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicblog',
            name='application_1',
            field=models.CharField(blank=True, default='Business Reporting: Create automated dashboards that update with new data', help_text='First application', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='application_2',
            field=models.CharField(blank=True, default='Financial Analysis: Build models with scenario analysis and forecasting', help_text='Second application', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='application_3',
            field=models.CharField(blank=True, default='Sales Tracking: Analyze performance and predict future trends', help_text='Third application', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='application_4',
            field=models.CharField(blank=True, default='Inventory Management: Track stock levels and optimize ordering', help_text='Fourth application', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='application_5',
            field=models.CharField(blank=True, default='Project Management: Create Gantt charts and track project timelines', help_text='Fifth application', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='cta_button_text',
            field=models.CharField(blank=True, default='Explore Course', help_text='Button text for call to action', max_length=100),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='cta_description',
            field=models.CharField(blank=True, default='Join our Excel for Data Analysis course today.', help_text='Call to action description', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='cta_link',
            field=models.CharField(blank=True, default='/courses/excel-data-analysis', help_text='Link for call to action button', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='cta_title',
            field=models.CharField(blank=True, default='Ready to Master Excel?', help_text='Call to action title', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='feature_1_description',
            field=models.TextField(blank=True, default='Transform data into insights, create dynamic reports, and use slicers for interactive filtering.', help_text='Description for first feature', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='feature_1_icon',
            field=models.CharField(default='bi-table', help_text='Icon for first feature', max_length=50),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='feature_1_title',
            field=models.CharField(blank=True, default='Pivot Tables', help_text='Title for first feature', max_length=100),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='feature_2_description',
            field=models.TextField(blank=True, default='Automate data cleaning, combine multiple sources, and create repeatable workflows.', help_text='Description for second feature', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='feature_2_icon',
            field=models.CharField(default='bi-lightning-charge', help_text='Icon for second feature', max_length=50),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='feature_2_title',
            field=models.CharField(blank=True, default='Power Query', help_text='Title for second feature', max_length=100),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='feature_3_description',
            field=models.TextField(blank=True, default='Master INDEX-MATCH, XLOOKUP, dynamic arrays, and statistical functions.', help_text='Description for third feature', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='feature_3_icon',
            field=models.CharField(default='bi-graph-up', help_text='Icon for third feature', max_length=50),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='feature_3_title',
            field=models.CharField(blank=True, default='Advanced Formulas', help_text='Title for third feature', max_length=100),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='feature_4_description',
            field=models.TextField(blank=True, default='Create compelling charts and dashboards that communicate insights effectively.', help_text='Description for fourth feature', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='feature_4_icon',
            field=models.CharField(default='bi-bar-chart', help_text='Icon for fourth feature', max_length=50),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='feature_4_title',
            field=models.CharField(blank=True, default='Data Visualization', help_text='Title for fourth feature', max_length=100),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='section_1_content',
            field=models.TextField(blank=True, help_text='Content for first section'),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='section_1_title',
            field=models.CharField(blank=True, default='Why Excel is Essential', help_text='Title for first content section', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='section_2_title',
            field=models.CharField(blank=True, default='Advanced Features to Master', help_text='Title for second content section', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='section_3_intro',
            field=models.TextField(blank=True, default='Excel skills translate directly to workplace success. Here are key applications:', help_text='Introduction for real-world applications'),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='section_3_title',
            field=models.CharField(blank=True, default='Real-World Applications', help_text='Title for third content section', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='section_4_conclusion',
            field=models.TextField(blank=True, default='Our Excel for Data Analysis course bridges classroom theory with industry needs. We focus on hands-on training for real-world challenges.', help_text='Conclusion for career impact section'),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='section_4_content',
            field=models.TextField(blank=True, default='Excel proficiency is among the top skills employers seek. Industry data shows:', help_text='Content for career impact section'),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='section_4_title',
            field=models.CharField(blank=True, default='Career Impact', help_text='Title for fourth content section', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='show_content_sections',
            field=models.BooleanField(default=True, help_text='Show content sections in blog detail'),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='stat_1_number',
            field=models.CharField(blank=True, default='82%', help_text='First statistic number', max_length=50),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='stat_1_text',
            field=models.CharField(blank=True, default='Jobs require Excel', help_text='Text for first statistic', max_length=100),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='stat_2_number',
            field=models.CharField(blank=True, default='35%', help_text='Second statistic number', max_length=50),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='stat_2_text',
            field=models.CharField(blank=True, default='Higher productivity', help_text='Text for second statistic', max_length=100),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='stat_3_number',
            field=models.CharField(blank=True, default='₹6-12L', help_text='Third statistic number', max_length=50),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='stat_3_text',
            field=models.CharField(blank=True, default='Salary boost', help_text='Text for third statistic', max_length=100),
        ),
    ]
