# Generated by Django 4.2.11 on 2026-01-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0047_dynamicblog_application_1_dynamicblog_application_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamicblog',
            old_name='feature_1_description',
            new_name='feature_1_content',
        ),
        migrations.RenameField(
            model_name='dynamicblog',
            old_name='feature_2_description',
            new_name='feature_2_content',
        ),
        migrations.RenameField(
            model_name='dynamicblog',
            old_name='feature_3_description',
            new_name='feature_3_content',
        ),
        migrations.RenameField(
            model_name='dynamicblog',
            old_name='feature_4_description',
            new_name='feature_4_content',
        ),
        migrations.RemoveField(
            model_name='dynamicblog',
            name='cta_link',
        ),
        migrations.RemoveField(
            model_name='dynamicblog',
            name='section_3_intro',
        ),
        migrations.RemoveField(
            model_name='dynamicblog',
            name='section_4_conclusion',
        ),
        migrations.RemoveField(
            model_name='dynamicblog',
            name='show_content_sections',
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='cta_button_link',
            field=models.CharField(blank=True, default='/courses/excel-data-analysis', help_text='URL for call to action button', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='show_cta',
            field=models.BooleanField(default=True, help_text='Show call to action section'),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='show_section_1',
            field=models.BooleanField(default=True, help_text='Show first content section'),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='show_section_2',
            field=models.BooleanField(default=True, help_text='Show features section'),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='show_section_3',
            field=models.BooleanField(default=True, help_text='Show applications section'),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='show_section_4',
            field=models.BooleanField(default=True, help_text='Show career impact section'),
        ),
        migrations.AlterField(
            model_name='dynamicblog',
            name='feature_1_icon',
            field=models.CharField(choices=[('bi-table', 'Table'), ('bi-lightning-charge', 'Lightning'), ('bi-graph-up', 'Graph Up'), ('bi-bar-chart', 'Bar Chart'), ('bi-briefcase', 'Briefcase'), ('bi-cash-coin', 'Money'), ('bi-people', 'People'), ('bi-gear', 'Gear'), ('bi-check-circle', 'Check Circle'), ('bi-star', 'Star'), ('bi-award', 'Award'), ('bi-clock', 'Clock'), ('bi-calendar', 'Calendar'), ('bi-chat', 'Chat'), ('bi-book', 'Book'), ('bi-laptop', 'Laptop'), ('bi-code', 'Code'), ('bi-shield', 'Shield'), ('bi-globe', 'Globe'), ('bi-heart', 'Heart')], default='bi-table', help_text='Icon for first feature', max_length=50),
        ),
        migrations.AlterField(
            model_name='dynamicblog',
            name='feature_1_title',
            field=models.CharField(blank=True, default='Pivot Tables', help_text='First feature title', max_length=100),
        ),
        migrations.AlterField(
            model_name='dynamicblog',
            name='feature_2_icon',
            field=models.CharField(choices=[('bi-table', 'Table'), ('bi-lightning-charge', 'Lightning'), ('bi-graph-up', 'Graph Up'), ('bi-bar-chart', 'Bar Chart'), ('bi-briefcase', 'Briefcase'), ('bi-cash-coin', 'Money'), ('bi-people', 'People'), ('bi-gear', 'Gear'), ('bi-check-circle', 'Check Circle'), ('bi-star', 'Star'), ('bi-award', 'Award'), ('bi-clock', 'Clock'), ('bi-calendar', 'Calendar'), ('bi-chat', 'Chat'), ('bi-book', 'Book'), ('bi-laptop', 'Laptop'), ('bi-code', 'Code'), ('bi-shield', 'Shield'), ('bi-globe', 'Globe'), ('bi-heart', 'Heart')], default='bi-lightning-charge', help_text='Icon for second feature', max_length=50),
        ),
        migrations.AlterField(
            model_name='dynamicblog',
            name='feature_2_title',
            field=models.CharField(blank=True, default='Power Query', help_text='Second feature title', max_length=100),
        ),
        migrations.AlterField(
            model_name='dynamicblog',
            name='feature_3_icon',
            field=models.CharField(choices=[('bi-table', 'Table'), ('bi-lightning-charge', 'Lightning'), ('bi-graph-up', 'Graph Up'), ('bi-bar-chart', 'Bar Chart'), ('bi-briefcase', 'Briefcase'), ('bi-cash-coin', 'Money'), ('bi-people', 'People'), ('bi-gear', 'Gear'), ('bi-check-circle', 'Check Circle'), ('bi-star', 'Star'), ('bi-award', 'Award'), ('bi-clock', 'Clock'), ('bi-calendar', 'Calendar'), ('bi-chat', 'Chat'), ('bi-book', 'Book'), ('bi-laptop', 'Laptop'), ('bi-code', 'Code'), ('bi-shield', 'Shield'), ('bi-globe', 'Globe'), ('bi-heart', 'Heart')], default='bi-graph-up', help_text='Icon for third feature', max_length=50),
        ),
        migrations.AlterField(
            model_name='dynamicblog',
            name='feature_3_title',
            field=models.CharField(blank=True, default='Advanced Formulas', help_text='Third feature title', max_length=100),
        ),
        migrations.AlterField(
            model_name='dynamicblog',
            name='feature_4_icon',
            field=models.CharField(choices=[('bi-table', 'Table'), ('bi-lightning-charge', 'Lightning'), ('bi-graph-up', 'Graph Up'), ('bi-bar-chart', 'Bar Chart'), ('bi-briefcase', 'Briefcase'), ('bi-cash-coin', 'Money'), ('bi-people', 'People'), ('bi-gear', 'Gear'), ('bi-check-circle', 'Check Circle'), ('bi-star', 'Star'), ('bi-award', 'Award'), ('bi-clock', 'Clock'), ('bi-calendar', 'Calendar'), ('bi-chat', 'Chat'), ('bi-book', 'Book'), ('bi-laptop', 'Laptop'), ('bi-code', 'Code'), ('bi-shield', 'Shield'), ('bi-globe', 'Globe'), ('bi-heart', 'Heart')], default='bi-bar-chart', help_text='Icon for fourth feature', max_length=50),
        ),
        migrations.AlterField(
            model_name='dynamicblog',
            name='feature_4_title',
            field=models.CharField(blank=True, default='Data Visualization', help_text='Fourth feature title', max_length=100),
        ),
        migrations.AlterField(
            model_name='dynamicblog',
            name='section_1_content',
            field=models.TextField(blank=True, default="Microsoft Excel remains one of the most powerful tools for data analysis in today's business environment. Despite new tools, Excel's versatility and accessibility make it indispensable for professionals.\n\nAt Yume Learning, we focus on practical, industry-aligned skills. Our Excel for Data Analysis course transforms theoretical knowledge into market-ready expertise that employers seek.", help_text='Content for first section'),
        ),
        migrations.AlterField(
            model_name='dynamicblog',
            name='section_4_content',
            field=models.TextField(blank=True, default='Excel proficiency is among the top skills employers seek. Industry data shows that our Excel for Data Analysis course bridges classroom theory with industry needs. We focus on hands-on training for real-world challenges.', help_text='Content for career impact section'),
        ),
        migrations.AlterField(
            model_name='dynamicblog',
            name='stat_1_text',
            field=models.CharField(blank=True, default='Jobs require Excel', help_text='First statistic text', max_length=100),
        ),
        migrations.AlterField(
            model_name='dynamicblog',
            name='stat_2_text',
            field=models.CharField(blank=True, default='Higher productivity', help_text='Second statistic text', max_length=100),
        ),
        migrations.AlterField(
            model_name='dynamicblog',
            name='stat_3_text',
            field=models.CharField(blank=True, default='Salary boost', help_text='Third statistic text', max_length=100),
        ),
    ]
