# Generated by Django 4.2.11 on 2026-01-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0048_rename_feature_1_description_dynamicblog_feature_1_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicblog',
            name='is_next_external',
            field=models.BooleanField(default=False, help_text='Check if next link is external URL (not Django URL name)'),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='is_previous_external',
            field=models.BooleanField(default=False, help_text='Check if previous link is external URL (not Django URL name)'),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='next_nav_label',
            field=models.CharField(blank=True, default='Next', help_text='Label for next navigation', max_length=100),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='next_nav_link',
            field=models.CharField(blank=True, default='sql_blog', help_text='URL name or path for next navigation (e.g., sql_blog for SQL Blog)', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='next_nav_text',
            field=models.CharField(blank=True, default='SQL for Data Analysis', help_text='Text for next navigation', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='previous_nav_label',
            field=models.CharField(blank=True, default='Previous', help_text='Label for previous navigation', max_length=100),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='previous_nav_link',
            field=models.CharField(blank=True, default='blog', help_text='URL name or path for previous navigation (e.g., blog for Blog List)', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='previous_nav_text',
            field=models.CharField(blank=True, default='Blog List', help_text='Text for previous navigation', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='show_blog_navigation',
            field=models.BooleanField(default=True, help_text='Show blog navigation section'),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='show_facebook_share',
            field=models.BooleanField(default=True, help_text='Show Facebook share button'),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='show_linkedin_share',
            field=models.BooleanField(default=True, help_text='Show LinkedIn share button'),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='show_social_share',
            field=models.BooleanField(default=True, help_text='Show social share section'),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='show_twitter_share',
            field=models.BooleanField(default=True, help_text='Show Twitter share button'),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='social_share_description',
            field=models.CharField(blank=True, default='Help others discover this valuable content', help_text='Description for social share section', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='social_share_title',
            field=models.CharField(blank=True, default='Share this article', help_text='Title for social share section', max_length=200),
        ),
    ]
