# Generated by Django 4.2.11 on 2026-01-13 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0049_dynamicblog_is_next_external_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicblog',
            name='azure_count',
            field=models.IntegerField(default=3, help_text='Number of Azure blog posts', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='career_count',
            field=models.IntegerField(default=2, help_text='Number of Career Tips blog posts', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='categories_section_title',
            field=models.CharField(blank=True, default='Blog Categories', help_text='Title for categories section', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='course_1_description',
            field=models.CharField(blank=True, default='Learn powerful Excel tools for data analysis', help_text='First course description', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='course_1_link',
            field=models.CharField(blank=True, default='/courses/excel-data-analysis', help_text='First course URL', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='course_1_title',
            field=models.CharField(blank=True, default='Excel for Data Analysis', help_text='First course title', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='course_2_description',
            field=models.CharField(blank=True, default='Create compelling visualizations', help_text='Second course description', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='course_2_link',
            field=models.CharField(blank=True, default='/courses/data-visualization', help_text='Second course URL', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='course_2_title',
            field=models.CharField(blank=True, default='Data Visualization', help_text='Second course title', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='course_3_description',
            field=models.CharField(blank=True, default='Extract and analyze data using SQL', help_text='Third course description', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='course_3_link',
            field=models.CharField(blank=True, default='/courses/sql-data-analysis', help_text='Third course URL', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='course_3_title',
            field=models.CharField(blank=True, default='SQL for Data Analysis', help_text='Third course title', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='courses_section_title',
            field=models.CharField(blank=True, default='Related Courses', help_text='Title for courses section', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='excel_count',
            field=models.IntegerField(default=6, help_text='Number of Excel blog posts', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='facebook_url',
            field=models.URLField(blank=True, default='https://www.facebook.com/yumelearning', help_text='Facebook page URL'),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://www.instagram.com/yumelearning/', help_text='Instagram profile URL'),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='linkedin_url',
            field=models.URLField(blank=True, default='https://www.linkedin.com/company/antsskillvarsity/', help_text='LinkedIn company page URL'),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='python_count',
            field=models.IntegerField(default=4, help_text='Number of Python blog posts', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='show_categories_section',
            field=models.BooleanField(default=True, help_text='Show blog categories section in sidebar'),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='show_courses_section',
            field=models.BooleanField(default=True, help_text='Show related courses section in sidebar'),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='show_social_section',
            field=models.BooleanField(default=True, help_text='Show social media section in sidebar'),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='social_description',
            field=models.CharField(blank=True, default='Stay updated with courses and career tips', help_text='Description under social icons', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='social_section_title',
            field=models.CharField(blank=True, default='Follow Yume Learning', help_text='Title for social media section', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicblog',
            name='sql_count',
            field=models.IntegerField(default=5, help_text='Number of SQL blog posts', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
