# Generated by Django 4.2.11 on 2026-01-15 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0050_dynamicblog_azure_count_dynamicblog_career_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('month', '📅 Month/Module'), ('section', '📋 Section/Week'), ('topic', '📝 Topic/Lesson')], default='month', help_text='Select type: Month, Section, or Topic', max_length=20)),
                ('title', models.CharField(help_text="e.g., 'Month 1', 'Week 1-2', 'Excel Interface'", max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text="e.g., 'Foundation Phase', 'Core Fundamentals'", max_length=255)),
                ('meta_info', models.CharField(blank=True, help_text="e.g., '40 Hours • Beginner Level'", max_length=100)),
                ('badge_color', models.CharField(choices=[('primary', 'Blue'), ('success', 'Green'), ('warning', 'Yellow'), ('danger', 'Red'), ('info', 'Light Blue'), ('secondary', 'Gray'), ('dark', 'Dark')], default='primary', help_text='Color for badge/header', max_length=20)),
                ('topic_description', models.TextField(blank=True, help_text='Detailed description for topics (optional)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within same level')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this item')),
                ('course', models.ForeignKey(help_text='Select which course this belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_items', to='yume_site.course')),
                ('parent', models.ForeignKey(blank=True, help_text='For topics: select which section this belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='yume_site.curriculumitem')),
            ],
            options={
                'verbose_name': 'Curriculum Item',
                'verbose_name_plural': 'Curriculum Items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='curriculumsection',
            name='month',
        ),
        migrations.RemoveField(
            model_name='curriculumtopic',
            name='section',
        ),
        migrations.DeleteModel(
            name='CurriculumMonth',
        ),
        migrations.DeleteModel(
            name='CurriculumSection',
        ),
        migrations.DeleteModel(
            name='CurriculumTopic',
        ),
    ]
