# Generated by Django 4.2.11 on 2026-01-15 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0051_curriculumitem_remove_curriculumsection_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Example: Month 1, Month 2', max_length=50)),
                ('subtitle', models.CharField(help_text='Example: Excel Foundations & Data Basics', max_length=255)),
                ('meta_info', models.CharField(blank=True, help_text='Example: 40 Hours • Beginner Level', max_length=100)),
                ('badge_color', models.CharField(choices=[('primary', 'Blue'), ('success', 'Green'), ('warning', 'Yellow'), ('danger', 'Red'), ('info', 'Light Blue'), ('secondary', 'Gray'), ('dark', 'Dark')], default='primary', help_text='Choose a color label for this month', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls the display order')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this month on website')),
                ('course', models.ForeignKey(help_text='Select which course this month belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_months', to='yume_site.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Example: Week 1–2: Core Fundamentals', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls section order inside the month')),
                ('month', models.ForeignKey(help_text='This section belongs to which month', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='yume_site.curriculummonth')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Example: Excel Interface & Navigation', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls topic order')),
                ('section', models.ForeignKey(help_text='This topic belongs to which section', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='yume_site.curriculumsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='CurriculumItem',
        ),
    ]
