# Generated by Django 4.2.11 on 2026-01-15 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0052_curriculummonth_curriculumsection_curriculumtopic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumsection',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Course this section belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_sections', to='yume_site.course'),
        ),
        migrations.AddField(
            model_name='curriculumtopic',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Course this topic belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_topics', to='yume_site.course'),
        ),
    ]
