# Generated by Django 4.2.11 on 2026-01-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0053_curriculumsection_course_curriculumtopic_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Slide title (e.g., Learn Future-Ready Skills)', max_length=200)),
                ('description', models.TextField(help_text='Slide description (keep it short)', max_length=300)),
                ('image', models.ImageField(help_text='Hero slider image (1920x1080px recommended)', upload_to='hero_slider/')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which slides appear (0 = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this slide in carousel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slider',
                'verbose_name_plural': 'Hero Slider',
                'ordering': ['display_order'],
            },
        ),
    ]
