# Generated by Django 4.2.11 on 2026-01-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0055_heroslide_delete_heroslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Advisor's full name (e.g., Dr. Ravi Shankar)", max_length=200)),
                ('image', models.ImageField(help_text='Profile photo of the advisor (recommended size: 350x380px)', upload_to='advisors/')),
                ('title', models.CharField(blank=True, default='Advisor & Mentor', help_text="Section title that appears above advisor's name", max_length=200)),
                ('bio_part1', models.TextField(help_text='First paragraph of biography (shown by default)')),
                ('bio_part2', models.TextField(blank=True, help_text='Second paragraph of biography (shown by default)')),
                ('bio_hidden1', models.TextField(blank=True, help_text='First hidden paragraph (shown when clicking Read More)')),
                ('bio_hidden2', models.TextField(blank=True, help_text='Second hidden paragraph (shown when clicking Read More)')),
                ('highlighted_phrases', models.TextField(blank=True, help_text="Words to highlight (one per line, e.g., 'global thought leader', 'Data Science & AI-ML')")),
                ('display_order', models.IntegerField(default=0, help_text='Order in which advisors appear (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this advisor on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advisor',
                'verbose_name_plural': 'Advisors',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
