# Generated by Django 4.2.11 on 2026-01-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0056_advisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='highlighted_phrases',
        ),
        migrations.AddField(
            model_name='advisor',
            name='keywords_to_highlight',
            field=models.TextField(blank=True, help_text='<strong>IMPORTANT FOR HR:</strong><br>List keywords that should appear in BLUE color in the text.<br>Enter one keyword per line.<br><br>Example keywords:<br>global thought leader<br>Data Science & AI-ML<br>IR4.0 technologies<br>AI-ML programs for CXOs<br>Visiting Professor<br>ISB<br>Singapore Management University'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Short description that appears under the name. Use • to separate roles.<br>Example: CO-FOUNDER • ANTS SKILL VARSITY • SOCIAL ENTREPRENEUR • SKILLING LEADER', max_length=300),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='bio_hidden1',
            field=models.TextField(blank=True, help_text='First hidden paragraph (shown when clicking Read More)<br><br>Tips for writing:<br>• Include co-founded ventures<br>• Mention past experiences<br>• Add industry-specific work<br><br>Example: He is actively involved in transforming the sugarcane industry from a net-zero perspective.'),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='bio_hidden2',
            field=models.TextField(blank=True, help_text='Second hidden paragraph (shown when clicking Read More)<br><br>Tips for writing:<br>• Add mentor/advisor roles<br>• Include board memberships<br>• Mention accelerators/incubators<br><br>Example: A seasoned AgTech mentor associated with multiple accelerators & incubators.'),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='bio_part1',
            field=models.TextField(help_text='First paragraph of biography (shown by default)<br><br>Tips for writing:<br>• Start with a strong introduction<br>• Mention their key expertise<br>• Use complete sentences<br><br>Example: Dr. Ravi Shankar is a global thought leader in framing accreditation and certification standards for Data Science & AI-ML.'),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='bio_part2',
            field=models.TextField(blank=True, help_text='Second paragraph of biography (shown by default)<br><br>Tips for writing:<br>• Mention current roles/positions<br>• Include specific institutions<br>• Highlight teaching specialties<br><br>Example: Currently a Visiting Professor at leading business institutes including ISB and Singapore Management University.'),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order in which advisors appear (0 = first, 1 = second, etc.)'),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='image',
            field=models.ImageField(help_text='Profile photo of the advisor (recommended size: 350x380px, JPG/PNG format)', upload_to='advisors/'),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='✓ Show this advisor on the website<br>✗ Hide this advisor from the website'),
        ),
    ]
