# Generated by Django 4.2.11 on 2026-01-21 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0057_remove_advisor_highlighted_phrases_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='yume_site.contactmessage')),
            ],
        ),
    ]
