# Generated by Django 4.2.11 on 2026-01-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0058_contactinformation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinformation',
            options={'verbose_name': 'Contact Information', 'verbose_name_plural': 'Contact Information'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contact'},
        ),
        migrations.RenameField(
            model_name='contactinformation',
            old_name='contact_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contactinformation',
            old_name='contact_phone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='contactinformation',
            name='contact_message',
        ),
    ]
