# Generated by Django 4.2.11 on 2026-01-22 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0059_alter_contactinformation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Where Our Students Build Careers', help_text='Main title for placements section', max_length=200)),
                ('subtitle', models.CharField(default='Successfully placed across leading tech, finance, and service sector companies.', help_text='Subtitle/description below title', max_length=300)),
                ('companies_count', models.IntegerField(default=50, help_text='Number of companies (e.g., 50+)')),
                ('students_placed', models.IntegerField(default=500, help_text='Number of students placed (e.g., 500+)')),
                ('sectors_count', models.IntegerField(default=10, help_text='Number of sectors (e.g., 10+)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this section on placements page')),
                ('display_order', models.IntegerField(default=1, help_text='Order in which sections appear (1 = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Placements Section',
                'verbose_name_plural': 'Placements Sections',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManyMoreCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_count', models.IntegerField(default=40, help_text='Number of additional companies (e.g., 40+)')),
                ('label', models.CharField(default='Leading Companies', help_text='Label below the count', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text="Show 'Many More' section")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placements_section', models.ForeignKey(help_text='Select placements section this belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='many_more_section', to='yume_site.placementssection')),
            ],
            options={
                'verbose_name': 'Many More Companies',
                'verbose_name_plural': 'Many More Companies Sections',
            },
        ),
        migrations.CreateModel(
            name='CompanyLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Company/organization name', max_length=100)),
                ('logo', models.ImageField(help_text='Company logo image', upload_to='placements/company_logos/')),
                ('alt_text', models.CharField(blank=True, help_text="Alternative text for accessibility (e.g., 'Infosys Logo')", max_length=100)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which logos appear (0 = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this company logo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placements_section', models.ForeignKey(help_text='Select placements section this logo belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='company_logos', to='yume_site.placementssection')),
            ],
            options={
                'verbose_name': 'Company Logo',
                'verbose_name_plural': 'Company Logos',
                'ordering': ['display_order', 'company_name'],
            },
        ),
    ]
