# Generated by Django 4.2.11 on 2026-01-23 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0060_placementssection_manymorecompanies_companylogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Career Launchpad', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Short description (keep it concise)', max_length=350)),
                ('partner_companies', models.PositiveIntegerField(default=300)),
                ('job_conversion_rate', models.PositiveIntegerField(default=85)),
                ('students_placed', models.PositiveIntegerField(default=1200)),
                ('display_order', models.PositiveIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Internship Section',
                'verbose_name_plural': 'Internship Section',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='InternshipBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(help_text='Keep it short', max_length=180)),
                ('icon', models.CharField(default='bi-briefcase', max_length=50)),
                ('icon_color', models.CharField(default='primary', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('internship_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='yume_site.internshipsection')),
            ],
            options={
                'verbose_name': 'Internship Benefit',
                'verbose_name_plural': 'Internship Benefits',
                'ordering': ['display_order'],
            },
        ),
    ]
