# Generated by Django 4.2.11 on 2026-01-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0061_internshipsection_internshipbenefit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipbenefit',
            name='description',
            field=models.CharField(help_text='Short one-line description', max_length=160),
        ),
        migrations.AlterField(
            model_name='internshipbenefit',
            name='icon',
            field=models.CharField(choices=[('bi-briefcase', '💼 Real Projects'), ('bi-people', '👥 Expert Mentorship'), ('bi-award', '🏆 Certification'), ('bi-graph-up', '📈 Career Growth'), ('bi-building', '🏢 Corporate Exposure'), ('bi-lightbulb', '💡 Skill Development')], default='bi-briefcase', max_length=50),
        ),
        migrations.AlterField(
            model_name='internshipbenefit',
            name='icon_color',
            field=models.CharField(choices=[('primary', 'Blue'), ('success', 'Green'), ('warning', 'Yellow'), ('info', 'Light Blue'), ('danger', 'Red'), ('secondary', 'Gray')], default='primary', max_length=20),
        ),
        migrations.AlterField(
            model_name='internshipsection',
            name='description',
            field=models.TextField(help_text='Short description shown under title', max_length=300),
        ),
    ]
