# Generated by Django 4.2.11 on 2026-02-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0062_alter_internshipbenefit_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the image (e.g., Coding Workshop)', max_length=200)),
                ('image', models.ImageField(help_text='Upload gallery image (recommended size: 800x600px)', upload_to='gallery/')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which images appear (0 = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this image in gallery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
