# Generated by Django 4.2.11 on 2026-02-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yume_site', '0063_galleryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='title',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for accessibility (optional)', max_length=200),
        ),
    ]
